-- Retrofit multiConnect: true on SRT ports for bundled-library cloud services
-- (AWS MediaConnect and AWS MediaLive). Aligns D1 with src/devices/cloud-services.ts.

UPDATE templates
   SET ports = '[{"id":"port-6105","label":"SRT Source","signalType":"srt","direction":"input","connectorType":"none","multiConnect":true},{"id":"port-6106","label":"RTP Source","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6107","label":"Zixi Source","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6108","label":"RIST Source","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6109","label":"SRT Output 1","signalType":"srt","direction":"output","connectorType":"none","multiConnect":true},{"id":"port-6110","label":"SRT Output 2","signalType":"srt","direction":"output","connectorType":"none","multiConnect":true},{"id":"port-6111","label":"RTP Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6112","label":"Zixi Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6113","label":"RIST Output","signalType":"ethernet","direction":"output","connectorType":"none"}]'
 WHERE id = 'c0a80101-00f5-4000-8000-000000000321';

UPDATE templates
   SET ports = '[{"id":"port-6114","label":"RTMP Push Input","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6115","label":"RTP Input","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6116","label":"HLS Input","signalType":"ethernet","direction":"input","connectorType":"none"},{"id":"port-6117","label":"MediaConnect Input","signalType":"srt","direction":"input","connectorType":"none","multiConnect":true},{"id":"port-6118","label":"HLS Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6119","label":"RTMP Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6120","label":"RTP Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6121","label":"MediaPackage Output","signalType":"ethernet","direction":"output","connectorType":"none"},{"id":"port-6122","label":"Archive Output","signalType":"ethernet","direction":"output","connectorType":"none"}]'
 WHERE id = 'c0a80101-00f6-4000-8000-000000000322';
