import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  {
    id: "c0a80101-00f1-4000-8000-000000000317",
    deviceType: "codec",
    label: "Cisco Room Kit",
    manufacturer: "Cisco",
    modelNumber: "CS-KIT-K9",
    referenceUrl: "https://www.cisco.com/c/en/us/products/collateral/collaboration-endpoints/spark-room-kit-series/datasheet-c78-738729.html",
    searchTerms: ["cisco", "room kit", "video conferencing", "webex", "collaboration"],
    powerDrawW: 100, // typical
    heightMm: 106,
    widthMm: 700,
    depthMm: 88,
    weightKg: 3.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("USB-A", "usb", "bidirectional", "usb-a"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00f2-4000-8000-000000000318",
    deviceType: "codec",
    label: "Cisco Codec Pro",
    manufacturer: "Cisco",
    modelNumber: "CS-CODEC-PRO-K9",
    referenceUrl: "https://help.webex.com/article/n86suwx/Get-started-with-your-Cisco-Codec-Pro",
    searchTerms: ["cisco", "codec pro", "video conferencing", "webex", "collaboration", "sdi"],
    powerDrawW: 200, // typical
    heightMm: 66,
    widthMm: 436,
    depthMm: 231,
    weightKg: 3.3,
    ports: [
      port("HDMI Cam In 1", "hdmi", "input"),
      port("HDMI Cam In 2", "hdmi", "input"),
      port("HDMI In 3", "hdmi", "input"),
      port("HDMI In 4", "hdmi", "input"),
      port("HDMI In 5", "hdmi", "input"),
      port("SDI Cam In", "sdi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("USB-A 1", "usb", "bidirectional", "usb-a"),
      port("USB-A 2", "usb", "bidirectional", "usb-a"),
      port("USB-B", "usb", "bidirectional", "usb-b"),
      port("Network", "ethernet", "bidirectional"),
      port("Cam Ctrl 1", "ethernet", "output"),
      port("Cam Ctrl 2", "ethernet", "output"),
      port("PoE", "ethernet", "output"),
      ...ports("Mic/Line In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Line Out", "analog-audio", "output", 6, "phoenix"),
      port("AC Power", "power", "input"),
      port("GPIO", "gpio", "bidirectional", "phoenix"),
    ],
  },
];
