import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Distribution Amp
  {
    id: "c0a80101-001d-4000-8000-000000000029",
    deviceType: "da",
    label: "Distribution Amp",
    powerDrawW: 5, // typical
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
    ],
  },
  // Datapath FX4 SDI — Video Wall Controller (SDI variant)
  {
    id: "c0a80101-0020-4000-8000-000000000032",
    deviceType: "video-wall-controller",
    label: "Datapath FX4 SDI",
    manufacturer: "Datapath",
    modelNumber: "FX4 SDI",
    referenceUrl: "https://www.datapath.co.uk/datapath-products/video-wall-controllers/datapath-fx4-sdi/",
    searchTerms: ["datapath", "video wall"],
    powerDrawW: 35,
    heightMm: 42,
    widthMm: 316,
    depthMm: 172,
    weightKg: 1.9,
    ports: [
      port("SDI In", "sdi", "input"),
      port("DP In", "displayport", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
      port("DP Loop", "displayport", "output"),
      port("AC Power", "power", "input"),
    
      port("Ethernet 1", "ethernet", "bidirectional"),
    
      port("Ethernet 2", "ethernet", "bidirectional"),
    
      port("USB-B", "usb", "bidirectional", "usb-b"),
    ],
  },
  // Datapath FX4 HDMI — Video Wall Controller
  {
    id: "c0a80101-0021-4000-8000-000000000033",
    deviceType: "video-wall-controller",
    label: "Datapath FX4 HDMI",
    manufacturer: "Datapath",
    modelNumber: "FX4 HDMI",
    referenceUrl: "https://www.datapath.co.uk/datapath-products/video-wall-controllers/datapath-fx4/",
    powerDrawW: 35,
    heightMm: 42,
    widthMm: 316,
    depthMm: 172,
    weightKg: 1.9,
    ports: [
      port("DP In", "displayport", "input"),
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("DP Loop", "displayport", "output"),
      port("AC Power", "power", "input"),
    
      port("Ethernet 1", "ethernet", "bidirectional"),
    
      port("Ethernet 2", "ethernet", "bidirectional"),
    
      port("USB-B", "usb", "bidirectional", "usb-b"),
    ],
  },
  {
    id: "c0a80101-0055-4000-8000-000000000085",
    deviceType: "da",
    label: "BMD SDI DA 1x8",
    manufacturer: "Blackmagic Design",
    modelNumber: "Mini Converter SDI Distribution",
    referenceUrl: "https://www.blackmagicdesign.com/products/miniconverters",
    searchTerms: ["blackmagic", "mini converter", "distribution", "da", "1x8"],
    powerDrawW: 5,
    heightMm: 28,
    widthMm: 92,
    depthMm: 72,
    weightKg: 0.1,
    ports: [
      port("SDI In", "sdi", "input"),
      ...ports("SDI Out", "sdi", "output", 8),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0056-4000-8000-000000000086",
    deviceType: "da",
    label: "BMD SDI DA 4K 1x8",
    manufacturer: "Blackmagic Design",
    modelNumber: "Mini Converter SDI Distribution 4K",
    referenceUrl: "https://www.blackmagicdesign.com/products/miniconverters",
    searchTerms: ["blackmagic", "mini converter", "distribution", "4k", "6g", "da"],
    powerDrawW: 5,
    heightMm: 28,
    widthMm: 92,
    depthMm: 72,
    weightKg: 0.1,
    ports: [
      port("SDI In", "sdi", "input"),
      ...ports("SDI Out", "sdi", "output", 8),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00fd-4000-8000-000000000329",
    deviceType: "da",
    category: "distribution",
    label: "BMD Teranex SDI Distribution 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini SDI Distribution 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini",
    searchTerms: ["blackmagic", "teranex", "distribution", "da", "12g"],
    powerDrawW: 16,
    heightMm: 45,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      port("SDI In", "sdi", "input"),
      ...ports("SDI Out", "sdi", "output", 8),
      port("AC Power", "power", "input"),
    ],
  },
  // Other new devices
  {
    id: "c0a80101-0113-4000-8000-000000000351",
    deviceType: "video-wall-controller",
    category: "video-processing",
    label: "Datapath Hx4",
    manufacturer: "Datapath",
    modelNumber: "Hx4",
    referenceUrl: "https://www.datapath.co.uk/products/video-wall-controllers/hx4/",
    searchTerms: ["datapath", "hx4", "video wall", "4k"],
    powerDrawW: 35, // typical
    heightMm: 42,
    widthMm: 316,
    depthMm: 172,
    weightKg: 1.9,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("DP Loop", "displayport", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB-B", "usb", "bidirectional", "usb-b"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0196-4000-8000-000000000406",
    deviceType: "da",
    category: "distribution",
    label: "AJA 12GDA",
    manufacturer: "AJA",
    modelNumber: "12GDA",
    referenceUrl: "https://www.aja.com/products/12gda",
    searchTerms: ["aja", "12gda", "distribution amplifier", "da", "12g", "sdi"],
    powerDrawW: 7, // typical
    heightMm: 25,
    widthMm: 147,
    depthMm: 79,
    weightKg: 0.3,
    ports: [
      port("12G-SDI In", "sdi", "input"),
      ...ports("12G-SDI Out", "sdi", "output", 6),
    ],
  },
  // Matrox TripleHead2Go — Graphics Expansion Modules (1-in 3-out)
  {
    id: "c0a80101-0304-4000-8000-000000000704",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox TripleHead2Go Digital Edition",
    manufacturer: "Matrox",
    modelNumber: "T2G-D3D-IF",
    referenceUrl: "https://www.matrox.com/en/video/products/graphics-expansion-modules/triplehead2go/digital-edition",
    searchTerms: ["matrox", "triplehead2go", "triple head", "th2go", "multi-monitor", "graphics expansion"],
    heightMm: 27,
    widthMm: 140,
    depthMm: 113,
    weightKg: 0.3,
    ports: [
      port("DVI In", "hdmi", "input", "dvi"),
      port("DVI Out 1", "hdmi", "output", "dvi"),
      port("DVI Out 2", "hdmi", "output", "dvi"),
      port("DVI Out 3", "hdmi", "output", "dvi"),
      port("USB Power", "usb", "input", "usb-b"),
    ],
  },
  {
    id: "c0a80101-0305-4000-8000-000000000705",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox TripleHead2Go Digital SE",
    manufacturer: "Matrox",
    modelNumber: "T2G-DP3D-IF",
    referenceUrl: "https://www.matrox.com/en/video/products/graphics-expansion-modules/triplehead2go/digital-se",
    searchTerms: ["matrox", "triplehead2go", "triple head", "th2go", "digital se", "multi-monitor", "graphics expansion"],
    heightMm: 28,
    widthMm: 64,
    depthMm: 135,
    weightKg: 0.2,
    ports: [
      port("DP In", "displayport", "input"),
      port("DVI Out 1", "hdmi", "output", "dvi"),
      port("DVI Out 2", "hdmi", "output", "dvi"),
      port("DVI Out 3", "hdmi", "output", "dvi"),
      port("USB Power", "usb", "input", "usb-b"),
    ],
  },
  {
    id: "c0a80101-0306-4000-8000-000000000706",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox TripleHead2Go DP Edition",
    manufacturer: "Matrox",
    modelNumber: "T2G-DP-MIF",
    referenceUrl: "https://www.matrox.com/en/video/products/graphics-expansion-modules/triplehead2go/dp-edition",
    searchTerms: ["matrox", "triplehead2go", "triple head", "th2go", "displayport", "multi-monitor", "graphics expansion"],
    heightMm: 28,
    widthMm: 89,
    depthMm: 97,
    weightKg: 0.1,
    ports: [
      port("DP In", "displayport", "input"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("USB Power", "usb", "input", "usb-b"),
    ],
  },
  // Matrox QuadHead2Go — Video Wall Controllers (1-in 4-out)
  {
    id: "c0a80101-0307-4000-8000-000000000707",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox QuadHead2Go Q155",
    manufacturer: "Matrox",
    modelNumber: "Q2G-H4K2",
    referenceUrl: "https://www.matrox.com/en/video/products/video-wall/quadhead2go/q155-appliance",
    searchTerms: ["matrox", "quadhead2go", "quad head", "qh2go", "q155", "video wall", "hdmi"],
    powerDrawW: 15,
    heightMm: 32,
    widthMm: 140,
    depthMm: 181,
    weightKg: 0.5,
    ports: [
      port("HDMI In", "hdmi", "input"),
      ...ports("HDMI Out", "hdmi", "output", 4),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0308-4000-8000-000000000708",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox QuadHead2Go Q155 Card",
    manufacturer: "Matrox",
    modelNumber: "Q2G-H4K-C",
    referenceUrl: "https://www.matrox.com/en/video/products/video-wall/quadhead2go/q155-card",
    searchTerms: ["matrox", "quadhead2go", "quad head", "qh2go", "q155", "video wall", "pcie", "card"],
    heightMm: 127,
    widthMm: 22,
    depthMm: 158,
    weightKg: 0.2,
    ports: [
      port("Mini HDMI In", "hdmi", "input", "mini-hdmi"),
      port("Mini HDMI Out 1", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 2", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 3", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 4", "hdmi", "output", "mini-hdmi"),
    ],
  },
  {
    id: "c0a80101-0309-4000-8000-000000000709",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox QuadHead2Go Q185",
    manufacturer: "Matrox",
    modelNumber: "Q2G-DP4K",
    referenceUrl: "https://www.matrox.com/en/video/products/video-wall/quadhead2go/q185-appliance",
    searchTerms: ["matrox", "quadhead2go", "quad head", "qh2go", "q185", "video wall", "displayport"],
    powerDrawW: 15,
    heightMm: 32,
    widthMm: 140,
    depthMm: 181,
    weightKg: 0.5,
    ports: [
      port("DP In", "displayport", "input"),
      ...ports("HDMI Out", "hdmi", "output", 4),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-030a-4000-8000-000000000710",
    deviceType: "video-wall-controller",
    category: "distribution",
    label: "Matrox QuadHead2Go Q185 Card",
    manufacturer: "Matrox",
    modelNumber: "Q2G-DP4K-C",
    referenceUrl: "https://www.matrox.com/en/video/products/video-wall/quadhead2go/q185-card",
    searchTerms: ["matrox", "quadhead2go", "quad head", "qh2go", "q185", "video wall", "displayport", "pcie", "card"],
    heightMm: 127,
    widthMm: 22,
    depthMm: 158,
    weightKg: 0.2,
    ports: [
      port("Mini DP In", "displayport", "input", "mini-displayport"),
      port("Mini HDMI Out 1", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 2", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 3", "hdmi", "output", "mini-hdmi"),
      port("Mini HDMI Out 4", "hdmi", "output", "mini-hdmi"),
    ],
  },
];
