import { port, camLokSet, patchPanelCircuits, wallPlatePorts } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Company Switches (venue-provided power sources)
  {
    id: "c0a80101-0300-4000-8000-000000000700",
    deviceType: "company-switch",
    label: "Company Switch 200A 3-Phase",
    isVenueProvided: true,
    searchTerms: ["company switch", "house power", "venue power", "tie-in", "200 amp", "3 phase", "service"],
    powerCapacityW: 72000,
    voltage: "208V 3-Phase",
    ports: [...camLokSet("output", "Cam-Lok", "3-Phase Output")],
  },
  {
    id: "c0a80101-0301-4000-8000-000000000701",
    deviceType: "company-switch",
    label: "Company Switch 400A 3-Phase",
    isVenueProvided: true,
    searchTerms: ["company switch", "house power", "venue power", "tie-in", "400 amp", "3 phase", "service", "main"],
    powerCapacityW: 144000,
    voltage: "208V 3-Phase",
    ports: [
      ...camLokSet("output", "Feed 1", "Feed 1"),
      ...camLokSet("output", "Feed 2", "Feed 2"),
    ],
  },
  {
    id: "c0a80101-0302-4000-8000-000000000702",
    deviceType: "company-switch",
    label: "Company Switch 100A Single Phase",
    isVenueProvided: true,
    searchTerms: ["company switch", "house power", "venue power", "tie-in", "100 amp", "single phase"],
    powerCapacityW: 12000,
    voltage: "120V",
    ports: [
      port("L1", "power-l1", "output", "cam-lok"),
      port("N", "power-neutral", "output", "cam-lok"),
      port("G", "power-ground", "output", "cam-lok"),
    ],
  },
  {
    id: "c0a80101-0303-4000-8000-000000000703",
    deviceType: "company-switch",
    label: "Wall Outlet / Convenience Power",
    isVenueProvided: true,
    searchTerms: ["wall outlet", "convenience power", "house power", "venue power", "edison", "wall plug"],
    powerCapacityW: 1800,
    voltage: "120V",
    ports: [
      port("Outlet 1", "power", "output", "edison"),
      port("Outlet 2", "power", "output", "edison"),
    ],
  },
  // Power Distribution
  {
    id: "c0a80101-003b-4000-8000-000000000059",
    deviceType: "power-distribution",
    label: "Power Strip",
    searchTerms: ["power strip", "power bar", "outlet strip", "surge protector"],
    powerCapacityW: 1800,
    voltage: "120V",
    ports: [
      port("AC In", "power", "input", "edison"),
      port("Out 1", "power", "output", "edison"),
      port("Out 2", "power", "output", "edison"),
      port("Out 3", "power", "output", "edison"),
      port("Out 4", "power", "output", "edison"),
      port("Out 5", "power", "output", "edison"),
      port("Out 6", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-003c-4000-8000-000000000060",
    deviceType: "power-distribution",
    label: "Rack PDU",
    searchTerms: ["pdu", "power distribution", "rack power"],
    powerCapacityW: 2400,
    voltage: "120V",
    ports: [
      port("AC In", "power", "input", "edison"),
      port("Out 1", "power", "output"),
      port("Out 2", "power", "output"),
      port("Out 3", "power", "output"),
      port("Out 4", "power", "output"),
      port("Out 5", "power", "output"),
      port("Out 6", "power", "output"),
      port("Out 7", "power", "output"),
      port("Out 8", "power", "output"),
      port("Out 9", "power", "output"),
      port("Out 10", "power", "output"),
      port("Out 11", "power", "output"),
      port("Out 12", "power", "output"),
    ],
  },
  {
    id: "c0a80101-003d-4000-8000-000000000061",
    deviceType: "power-distribution",
    label: "PowerCON Distro",
    searchTerms: ["powercon", "distro", "power distribution", "show power", "edison"],
    powerCapacityW: 2400,
    voltage: "120V",
    ports: [
      port("Power In", "power", "input", "powercon"),
      port("Out 1", "power", "output", "edison"),
      port("Out 2", "power", "output", "edison"),
      port("Out 3", "power", "output", "edison"),
      port("Out 4", "power", "output", "edison"),
      port("Out 5", "power", "output", "edison"),
      port("Out 6", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-003e-4000-8000-000000000062",
    deviceType: "power-distribution",
    label: "PowerCON Thru Distro",
    searchTerms: ["powercon", "distro", "thru", "daisy chain", "lighting power"],
    powerCapacityW: 2400,
    voltage: "120V",
    ports: [
      port("Power In", "power", "input", "powercon"),
      port("Power Thru", "power", "output", "powercon"),
      port("Out 1", "power", "output", "powercon"),
      port("Out 2", "power", "output", "powercon"),
      port("Out 3", "power", "output", "powercon"),
      port("Out 4", "power", "output", "powercon"),
      port("Out 5", "power", "output", "powercon"),
      port("Out 6", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-021b-4000-8000-000000000539",
    deviceType: "power-distribution",
    label: "Lex DB-100",
    manufacturer: "Lex Products",
    modelNumber: "DB-100",
    searchTerms: ["lex", "db100", "100 amp", "distro", "cam-lok", "power distribution"],
    powerCapacityW: 20800,
    voltage: "208V",
    heightMm: 359,
    widthMm: 362,
    depthMm: 362,
    weightKg: 14.5,
    ports: [
      ...camLokSet("input", "Cam-Lok In", "3-Phase Input"),
      port("L5-20 Out 1", "power", "output", "l5-20"),
      port("L5-20 Out 2", "power", "output", "l5-20"),
      port("L5-20 Out 3", "power", "output", "l5-20"),
      port("L5-20 Out 4", "power", "output", "l5-20"),
      port("L5-20 Out 5", "power", "output", "l5-20"),
      port("L5-20 Out 6", "power", "output", "l5-20"),
      port("L6-20 Out 1", "power", "output", "l6-20"),
      port("L6-20 Out 2", "power", "output", "l6-20"),
      port("L6-20 Out 3", "power", "output", "l6-20"),
      port("L6-20 Out 4", "power", "output", "l6-20"),
      port("L6-20 Out 5", "power", "output", "l6-20"),
      port("L6-20 Out 6", "power", "output", "l6-20"),
    ],
  },
  {
    id: "c0a80101-021c-4000-8000-000000000540",
    deviceType: "power-distribution",
    label: "Lex DB-200",
    manufacturer: "Lex Products",
    modelNumber: "DB-200",
    searchTerms: ["lex", "db200", "200 amp", "distro", "cam-lok", "power distribution"],
    powerCapacityW: 41600,
    voltage: "208V",
    heightMm: 359,
    widthMm: 362,
    depthMm: 362,
    weightKg: 15.9,
    ports: [
      ...camLokSet("input", "Cam-Lok In", "3-Phase Input"),
      port("L5-20 Out 1", "power", "output", "l5-20"),
      port("L5-20 Out 2", "power", "output", "l5-20"),
      port("L5-20 Out 3", "power", "output", "l5-20"),
      port("L5-20 Out 4", "power", "output", "l5-20"),
      port("L5-20 Out 5", "power", "output", "l5-20"),
      port("L5-20 Out 6", "power", "output", "l5-20"),
      port("L6-20 Out 1", "power", "output", "l6-20"),
      port("L6-20 Out 2", "power", "output", "l6-20"),
      port("L6-20 Out 3", "power", "output", "l6-20"),
      port("L6-20 Out 4", "power", "output", "l6-20"),
      port("L6-20 Out 5", "power", "output", "l6-20"),
      port("L6-20 Out 6", "power", "output", "l6-20"),
      port("L6-20 Out 7", "power", "output", "l6-20"),
      port("L6-20 Out 8", "power", "output", "l6-20"),
    ],
  },
  {
    id: "c0a80101-021d-4000-8000-000000000541",
    deviceType: "power-distribution",
    label: "Lex Hammerhead 400A Splitter",
    manufacturer: "Lex Products",
    modelNumber: "DB400N1J4AJ2CC-63",
    searchTerms: ["lex", "hammerhead", "cam-lok", "400 amp", "breakout", "splitter", "power distribution"],
    powerCapacityW: 83200,
    voltage: "208V",
    heightMm: 559,
    widthMm: 457,
    depthMm: 381,
    weightKg: 34,
    ports: [
      ...camLokSet("input", "Cam-Lok In", "400A Input"),
      ...camLokSet("output", "100A Out 1", "100A Feed 1"),
      ...camLokSet("output", "100A Out 2", "100A Feed 2"),
      ...camLokSet("output", "100A Out 3", "100A Feed 3"),
      ...camLokSet("output", "100A Out 4", "100A Feed 4"),
    ],
  },
  {
    id: "c0a80101-021e-4000-8000-000000000542",
    deviceType: "power-distribution",
    label: "208V Panel (42-ckt)",
    searchTerms: ["208v panel", "42 circuit", "breaker panel", "power panel", "power distribution"],
    powerCapacityW: 43200,
    voltage: "208V",
    ports: [
      port("L21-30 In", "power", "input", "l21-30"),
      ...Array.from({ length: 12 }, (_, i) => port(`L6-20 Out ${i + 1}`, "power", "output" as const, "l6-20" as const)),
    ],
  },
  {
    id: "c0a80101-021f-4000-8000-000000000543",
    deviceType: "power-distribution",
    label: "Socapex Breakout",
    searchTerms: ["socapex", "breakout", "soca", "lighting power", "power distribution"],
    powerCapacityW: 14400,
    voltage: "120V",
    ports: [
      port("Socapex In", "power", "input", "socapex"),
      port("Edison Out 1", "power", "output", "edison"),
      port("Edison Out 2", "power", "output", "edison"),
      port("Edison Out 3", "power", "output", "edison"),
      port("Edison Out 4", "power", "output", "edison"),
      port("Edison Out 5", "power", "output", "edison"),
      port("Edison Out 6", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-0220-4000-8000-000000000544",
    deviceType: "power-distribution",
    label: "Rack PDU 208V",
    searchTerms: ["pdu", "208v", "rack power", "iec", "data center", "power distribution"],
    powerCapacityW: 4992,
    voltage: "208V",
    ports: [
      port("L6-30 In", "power", "input", "l6-30"),
      port("IEC Out 1", "power", "output", "iec"),
      port("IEC Out 2", "power", "output", "iec"),
      port("IEC Out 3", "power", "output", "iec"),
      port("IEC Out 4", "power", "output", "iec"),
      port("IEC Out 5", "power", "output", "iec"),
      port("IEC Out 6", "power", "output", "iec"),
      port("IEC Out 7", "power", "output", "iec"),
      port("IEC Out 8", "power", "output", "iec"),
    ],
  },
  {
    id: "c0a80101-0221-4000-8000-000000000545",
    deviceType: "power-distribution",
    label: "Portable 60A Distro",
    searchTerms: ["60 amp", "portable", "distro", "spider", "power distribution"],
    powerCapacityW: 7200,
    voltage: "120V",
    ports: [
      port("L5-20 In", "power", "input", "l5-20"),
      port("Edison Out 1", "power", "output", "edison"),
      port("Edison Out 2", "power", "output", "edison"),
      port("Edison Out 3", "power", "output", "edison"),
      port("Edison Out 4", "power", "output", "edison"),
      port("Edison Out 5", "power", "output", "edison"),
      port("Edison Out 6", "power", "output", "edison"),
    ],
  },
  // Patch Panels
  {
    id: "c0a80101-00e8-4000-8000-000000000308",
    deviceType: "patch-panel",
    label: "Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "rj45", "ethernet", "cat6"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 12, { signalType: "ethernet", rearConnectorType: "rj45", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-00e9-4000-8000-000000000309",
    deviceType: "patch-panel",
    label: "Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "rj45", "ethernet", "cat6"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 24, { signalType: "ethernet", rearConnectorType: "rj45", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-00ea-4000-8000-000000000310",
    deviceType: "patch-panel",
    label: "Patch Panel 48-Port",
    searchTerms: ["patch panel", "patch bay", "48 port", "rj45", "ethernet", "cat6"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 48, { signalType: "ethernet", rearConnectorType: "rj45", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-00eb-4000-8000-000000000311",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "bnc", "sdi", "video"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 12, { signalType: "sdi", rearConnectorType: "bnc", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-00ec-4000-8000-000000000312",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "bnc", "sdi", "video"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 24, { signalType: "sdi", rearConnectorType: "bnc", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-00ed-4000-8000-000000000313",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "xlr", "audio", "analog"],
    powerDrawW: 0,
    // Both faces female — pro-audio convention for a generic XLR bay.
    ports: patchPanelCircuits("Port ", 12, { signalType: "analog-audio", rearConnectorType: "xlr-3", frontConnectorType: "xlr-3", rearGender: "female", frontGender: "female" }),
  },
  {
    id: "c0a80101-00ee-4000-8000-000000000314",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "xlr", "audio", "analog"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 24, { signalType: "analog-audio", rearConnectorType: "xlr-3", frontConnectorType: "xlr-3", rearGender: "female", frontGender: "female" }),
  },
  {
    id: "c0a80101-00ef-4000-8000-000000000315",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "fiber", "lc", "optical"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 12, { signalType: "fiber", rearConnectorType: "lc", frontConnectorType: "lc" }),
  },
  {
    id: "c0a80101-00f0-4000-8000-000000000316",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "fiber", "lc", "optical"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 24, { signalType: "fiber", rearConnectorType: "lc", frontConnectorType: "lc" }),
  },
  {
    id: "c0a80101-0230-4000-8000-000000000711",
    deviceType: "patch-panel",
    label: "Patch Panel 32-Port",
    searchTerms: ["patch panel", "patch bay", "32 port", "rj45", "ethernet", "cat6", "networx"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 32, { signalType: "ethernet", rearConnectorType: "rj45", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-0231-4000-8000-000000000712",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 32-Port",
    searchTerms: ["patch panel", "patch bay", "32 port", "bnc", "sdi", "video"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 32, { signalType: "sdi", rearConnectorType: "bnc", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-0232-4000-8000-000000000713",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 48-Port",
    searchTerms: ["patch panel", "patch bay", "48 port", "bnc", "sdi", "video"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 48, { signalType: "sdi", rearConnectorType: "bnc", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-0233-4000-8000-000000000714",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 32-Port",
    searchTerms: ["patch panel", "patch bay", "32 port", "xlr", "audio", "analog"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 32, { signalType: "analog-audio", rearConnectorType: "xlr-3", frontConnectorType: "xlr-3", rearGender: "female", frontGender: "female" }),
  },
  {
    id: "c0a80101-0234-4000-8000-000000000715",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 48-Port",
    searchTerms: ["patch panel", "patch bay", "48 port", "xlr", "audio", "analog"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 48, { signalType: "analog-audio", rearConnectorType: "xlr-3", frontConnectorType: "xlr-3", rearGender: "female", frontGender: "female" }),
  },
  {
    id: "c0a80101-0235-4000-8000-000000000716",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 32-Port",
    searchTerms: ["patch panel", "patch bay", "32 port", "fiber", "lc", "optical"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 32, { signalType: "fiber", rearConnectorType: "lc", frontConnectorType: "lc" }),
  },
  {
    id: "c0a80101-0236-4000-8000-000000000717",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 48-Port",
    searchTerms: ["patch panel", "patch bay", "48 port", "fiber", "lc", "optical"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 48, { signalType: "fiber", rearConnectorType: "lc", frontConnectorType: "lc" }),
  },
  {
    id: "c0a80101-0237-4000-8000-000000000718",
    deviceType: "patch-panel",
    label: "TRS Patch Bay 24-Point",
    searchTerms: ["patch bay", "patch panel", "24 point", "trs", "quarter inch", "audio", "tt", "bantam", "normalled"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 24, { signalType: "analog-audio", rearConnectorType: "trs-quarter", frontConnectorType: "trs-quarter" }),
  },
  {
    id: "c0a80101-0238-4000-8000-000000000719",
    deviceType: "patch-panel",
    label: "TRS Patch Bay 48-Point",
    searchTerms: ["patch bay", "patch panel", "48 point", "trs", "quarter inch", "audio", "tt", "bantam", "normalled"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 48, { signalType: "analog-audio", rearConnectorType: "trs-quarter", frontConnectorType: "trs-quarter" }),
  },
  {
    id: "c0a80101-0239-4000-8000-000000000720",
    deviceType: "patch-panel",
    label: "TRS Patch Bay 96-Point",
    searchTerms: ["patch bay", "patch panel", "96 point", "trs", "quarter inch", "audio", "tt", "bantam", "normalled"],
    powerDrawW: 0,
    ports: patchPanelCircuits("Port ", 96, { signalType: "analog-audio", rearConnectorType: "trs-quarter", frontConnectorType: "trs-quarter" }),
  },
  // Wall Plates
  {
    id: "c0a80101-0240-4000-8000-000000000721",
    deviceType: "wall-plate",
    label: "Wall Plate 1-Port Keystone",
    searchTerms: ["wall plate", "keystone", "1 port", "rj45", "ethernet", "cat6", "single gang"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 1, { signalType: "ethernet", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-0241-4000-8000-000000000722",
    deviceType: "wall-plate",
    label: "Wall Plate 2-Port Keystone",
    searchTerms: ["wall plate", "keystone", "2 port", "rj45", "ethernet", "cat6", "single gang", "dual"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 2, { signalType: "ethernet", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-0242-4000-8000-000000000723",
    deviceType: "wall-plate",
    label: "Wall Plate 4-Port Keystone",
    searchTerms: ["wall plate", "keystone", "4 port", "rj45", "ethernet", "cat6", "dual gang", "quad"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 4, { signalType: "ethernet", frontConnectorType: "rj45" }),
  },
  {
    id: "c0a80101-0243-4000-8000-000000000724",
    deviceType: "wall-plate",
    label: "Wall Plate 1-Port BNC",
    searchTerms: ["wall plate", "keystone", "1 port", "bnc", "sdi", "video", "single gang"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 1, { signalType: "sdi", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-0244-4000-8000-000000000725",
    deviceType: "wall-plate",
    label: "Wall Plate 2-Port BNC",
    searchTerms: ["wall plate", "keystone", "2 port", "bnc", "sdi", "video", "dual"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 2, { signalType: "sdi", frontConnectorType: "bnc" }),
  },
  {
    id: "c0a80101-0245-4000-8000-000000000726",
    deviceType: "wall-plate",
    label: "Wall Plate 1-Port XLR",
    searchTerms: ["wall plate", "xlr", "1 port", "audio", "analog", "single gang"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 1, { signalType: "analog-audio", frontConnectorType: "xlr-3" }),
  },
  {
    id: "c0a80101-0246-4000-8000-000000000727",
    deviceType: "wall-plate",
    label: "Wall Plate 2-Port XLR",
    searchTerms: ["wall plate", "xlr", "2 port", "audio", "analog", "dual gang"],
    powerDrawW: 0,
    ports: wallPlatePorts("Port ", 2, { signalType: "analog-audio", frontConnectorType: "xlr-3" }),
  },
];
