import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── LED Processors ───────────────────────────────────────────────
  {
    id: "c0a80101-00b3-4000-8000-000000000179",
    deviceType: "led-processor",
    label: "Brompton Tessera SX40",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera SX40",
    referenceUrl: "https://www.bromptontech.com/product/sx40/",
    searchTerms: ["brompton", "tessera", "sx40", "led processor", "led wall"],
    powerDrawW: 250, // typical
    heightMm: 89,
    widthMm: 483,
    depthMm: 406,
    weightKg: 7.5,
    ports: [
      port("12G-SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("LED Out 1", "ethernet", "output", "opticalcon"),
      port("LED Out 2", "ethernet", "output", "opticalcon"),
      port("LED Out 3", "ethernet", "output", "opticalcon"),
      port("LED Out 4", "ethernet", "output", "opticalcon"),
      port("LED Out 5", "ethernet", "output", "ethercon"),
      port("LED Out 6", "ethernet", "output", "ethercon"),
      port("LED Out 7", "ethernet", "output", "ethercon"),
      port("LED Out 8", "ethernet", "output", "ethercon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b4-4000-8000-000000000180",
    deviceType: "led-processor",
    label: "Brompton Tessera S4",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera S4",
    referenceUrl: "https://www.bromptontech.com/product/s4/",
    searchTerms: ["brompton", "tessera", "s4", "led processor"],
    powerDrawW: 60, // typical
    heightMm: 50,
    widthMm: 483,
    depthMm: 384,
    weightKg: 4.5,
    ports: [
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("LED Out 1", "ethernet", "output", "rj45"),
      port("LED Out 2", "ethernet", "output", "rj45"),
      port("LED Out 3", "ethernet", "output", "rj45"),
      port("LED Out 4", "ethernet", "output", "rj45"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b5-4000-8000-000000000181",
    deviceType: "led-processor",
    label: "Brompton Tessera M2",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera M2",
    referenceUrl: "https://www.bromptontech.com/product/r2-plus/",
    searchTerms: ["brompton", "tessera", "m2", "receiver card", "led"],
    powerDrawW: 5, // typical — powered via LED panel
    heightMm: 89,
    widthMm: 483,
    depthMm: 508,
    ports: [
      port("LED Data In", "ethernet", "input"),
      port("LED Data Link", "ethernet", "output"),
    ],
  },
  {
    id: "c0a80101-00b6-4000-8000-000000000182",
    deviceType: "led-processor",
    label: "Novastar NovaPro HD",
    manufacturer: "Novastar",
    modelNumber: "NovaPro HD",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=36",
    searchTerms: ["novastar", "novapro", "led processor", "led wall"],
    powerDrawW: 120, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 389,
    weightKg: 6,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("DVI In", "hdmi", "input", "dvi"),
      port("DP In", "displayport", "input"),
      port("VGA In", "vga", "input"),
      port("Composite In", "composite", "input"),
      port("Genlock In", "genlock", "input"),
      port("Audio In", "analog-audio", "input", "trs-eighth"),
      port("LED Out 1", "ethernet", "output"),
      port("LED Out 2", "ethernet", "output"),
      port("LED Out 3", "ethernet", "output"),
      port("LED Out 4", "ethernet", "output"),
      port("Fiber Out 1", "fiber", "output", "lc"),
      port("Fiber Out 2", "fiber", "output", "lc"),
      port("Fiber Out 3", "fiber", "output", "lc"),
      port("Fiber Out 4", "fiber", "output", "lc"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b7-4000-8000-000000000183",
    deviceType: "led-processor",
    label: "Novastar VX2000 Pro",
    manufacturer: "Novastar",
    modelNumber: "VX2000 Pro",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=34",
    searchTerms: ["novastar", "vx2000", "led processor", "all-in-one"],
    powerDrawW: 300, // typical
    heightMm: 95,
    widthMm: 483,
    depthMm: 409,
    weightKg: 7,
    ports: [
      port("HDMI 2.0 In 1", "hdmi", "input"),
      port("HDMI 2.0 In 2", "hdmi", "input"),
      port("HDMI 1.3 In 1", "hdmi", "input"),
      port("HDMI 1.3 In 2", "hdmi", "input"),
      port("HDMI 1.3 In 3", "hdmi", "input"),
      port("HDMI 1.3 In 4", "hdmi", "input"),
      port("12G-SDI In", "sdi", "input"),
      port("DP 1.2 In", "displayport", "input"),
      port("Genlock In", "genlock", "input"),
      ...ports("LED Out", "ethernet", "output", 20),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-010d-4000-8000-000000000345
    // with Disguise VX 2 in src/devices/media-servers.ts, which wins the dedupe
    // (D1 keeps the last-seeded row), leaving this processor unreachable.
    id: "c0a80101-0316-4000-8000-000000000744",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Novastar NovaPro UHD Jr",
    manufacturer: "Novastar",
    modelNumber: "NovaPro UHD Jr",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=36",
    searchTerms: ["novastar", "novapro", "uhd", "led processor"],
    powerDrawW: 150, // typical
    heightMm: 139,
    widthMm: 483,
    depthMm: 396,
    weightKg: 6.3,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("SDI In", "sdi", "input"),
      port("Genlock In", "genlock", "input"),
      ...ports("LED Out", "ethernet", "output", 16),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-030b-4000-8000-000000000711",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Novastar MX30",
    manufacturer: "Novastar",
    modelNumber: "MX30",
    referenceUrl:
      "https://oss.novastar.tech/uploads/2025/09/MX30-LED-Display-Controller-Specifications-V1.5.0.pdf",
    searchTerms: ["novastar", "mx30", "coex", "led processor", "all-in-one", "vmp"],
    powerDrawW: 55, // max
    voltage: "100-240V",
    heightMm: 94.2,
    widthMm: 483,
    depthMm: 466.7,
    weightKg: 7.2,
    ports: [
      port("HDMI 2.0-1 In", "hdmi", "input"),
      port("HDMI 1.4-2 In", "hdmi", "input"),
      port("DP 1.1 In", "displayport", "input"),
      port("3G-SDI In 1", "sdi", "input"),
      port("3G-SDI In 2", "sdi", "input"),
      port("Genlock In", "genlock", "input"),
      port("HDMI 2.0-1 Loop", "hdmi", "output"),
      port("HDMI 1.4-2 Loop", "hdmi", "output"),
      port("3G-SDI Loop 1", "sdi", "output"),
      port("3G-SDI Loop 2", "sdi", "output"),
      port("Genlock Loop", "genlock", "output"),
      ...ports("LED Out", "ethernet", "output", 10, "rj45"),
      port("SPDIF Out", "spdif", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Aux (RS232)", "serial", "bidirectional", "other"), // connector type not published
      port("USB 2.0", "usb", "input", "usb-a"), // front panel — diagnostic export
      port("AC Power", "power", "input"),
    ],
    slots: [
      // 10G optical outs — no module fitted from the factory
      { id: "sfp-1", label: "OPT 1", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-2", label: "OPT 2", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-010e-4000-8000-000000000346
    // with Disguise VX 3 in src/devices/media-servers.ts, which wins the dedupe.
    id: "c0a80101-0317-4000-8000-000000000745",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera S8",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera S8",
    referenceUrl: "https://www.bromptontech.com/product/s8/",
    searchTerms: ["brompton", "tessera", "s8", "led processor"],
    powerDrawW: 120, // typical
    heightMm: 89,
    widthMm: 483,
    depthMm: 508,
    weightKg: 7.5,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("SDI In", "sdi", "input"),
      port("Genlock In", "genlock", "input"),
      port("LED Out 1", "ethernet", "output", "ethercon"),
      port("LED Out 2", "ethernet", "output", "ethercon"),
      port("LED Out 3", "ethernet", "output", "ethercon"),
      port("LED Out 4", "ethernet", "output", "ethercon"),
      port("LED Out 5", "ethernet", "output", "ethercon"),
      port("LED Out 6", "ethernet", "output", "ethercon"),
      port("LED Out 7", "ethernet", "output", "ethercon"),
      port("LED Out 8", "ethernet", "output", "ethercon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-010f-4000-8000-000000000347
    // with Disguise GX 1 in src/devices/media-servers.ts, which wins the dedupe.
    id: "c0a80101-0318-4000-8000-000000000746",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera R2+",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera R2+",
    referenceUrl: "https://www.bromptontech.com/product/r2-plus/",
    searchTerms: ["brompton", "tessera", "r2", "receiver", "led"],
    powerDrawW: 5, // typical — powered via LED panel
    widthMm: 68,
    depthMm: 32,
    ports: [
      port("Data In", "ethernet", "input", "ethercon"),
      port("Data Out", "ethernet", "output", "ethercon"),
    ],
  },
  {
    id: "c0a80101-0187-4000-8000-000000000391",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera XD 10G",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera XD 10G",
    referenceUrl: "https://www.bromptontech.com/product/xd/",
    searchTerms: ["brompton", "tessera", "xd", "10g", "distribution", "led"],
    powerDrawW: 80, // typical
    heightMm: 89,
    widthMm: 483,
    depthMm: 210,
    weightKg: 10,
    ports: [
      port("10G Copper In", "ethernet", "input", "rj45"),
      ...ports("LED Out", "ethernet", "output", 10, "rj45"),
      port("AC Power", "power", "input"),
    ],
    slots: [
      { id: "sfp-1", label: "10G Fiber In", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-2", label: "10G Thru", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
  {
    id: "c0a80101-0188-4000-8000-000000000392",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Megapixel HELIOS",
    manufacturer: "Megapixel",
    modelNumber: "HELIOS",
    referenceUrl: "https://megapixelvr.com/helios/",
    searchTerms: ["megapixel", "helios", "led processor", "led wall", "virtual production"],
    powerDrawW: 500, // typical
    heightMm: 184,
    widthMm: 533,
    depthMm: 597,
    weightKg: 8.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
    slots: [
      { id: "qsfp-1", label: "QSFP Fiber In", slotFamily: "qsfp", defaultCardId: "qsfp-40g-sr4" },
      { id: "sfp-1", label: "SFP+ Slot 1", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-2", label: "SFP+ Slot 2", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-3", label: "SFP+ Slot 3", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-4", label: "SFP+ Slot 4", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-5", label: "10G Fiber Out 1", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-6", label: "10G Fiber Out 2", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-7", label: "10G Fiber Out 3", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-8", label: "10G Fiber Out 4", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-9", label: "10G Fiber Out 5", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-10", label: "10G Fiber Out 6", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-11", label: "10G Fiber Out 7", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "sfp-12", label: "10G Fiber Out 8", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
];
