import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Blackmagic Micro Converter SDI to HDMI
  {
    id: "c0a80101-0006-4000-8000-000000000006",
    deviceType: "converter",
    label: "BMD SDI→HDMI",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter SDI to HDMI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-12",
    searchTerms: ["blackmagic", "micro converter", "microconverter"],
    powerDrawW: 2,
    heightMm: 25,
    widthMm: 77,
    depthMm: 46,
    weightKg: 0.2,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Loop", "sdi", "output"),
    ],
  },
  // Blackmagic Micro Converter HDMI to SDI
  {
    id: "c0a80101-0007-4000-8000-000000000007",
    deviceType: "converter",
    label: "BMD HDMI→SDI",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter HDMI to SDI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-11",
    searchTerms: ["blackmagic", "micro converter", "microconverter"],
    powerDrawW: 2,
    heightMm: 25,
    widthMm: 77,
    depthMm: 46,
    weightKg: 0.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
    ],
  },
  // Decimator MD-LX — Bidirectional SDI/HDMI Cross Converter
  {
    id: "c0a80101-0008-4000-8000-000000000008",
    deviceType: "converter",
    label: "Decimator MD-LX",
    manufacturer: "Decimator Design",
    modelNumber: "MD-LX",
    referenceUrl: "https://decimator.com/Products/MiniConverters/MD-LX/MD-LX.html",
    searchTerms: ["decimator", "cross converter", "bidirectional"],
    powerDrawW: 2, // typical
    heightMm: 23,
    widthMm: 60,
    depthMm: 74,
    weightKg: 0.4,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Blackmagic Micro Converter BiDirectional SDI/HDMI 3G
  {
    id: "c0a80101-0009-4000-8000-000000000009",
    deviceType: "converter",
    label: "BMD BiDir SDI/HDMI 3G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter BiDirectional SDI/HDMI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-09",
    searchTerms: ["blackmagic", "micro converter", "bidirectional", "3g"],
    powerDrawW: 3,
    heightMm: 25,
    widthMm: 81,
    depthMm: 59,
    weightKg: 0.2,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // AJA FiDO-4T — Quad SDI to Fiber Transmitter
  {
    id: "c0a80101-000a-4000-8000-000000000010",
    deviceType: "converter",
    label: "AJA FiDO-4T",
    manufacturer: "AJA",
    modelNumber: "FiDO-4T",
    referenceUrl: "https://www.aja.com/products/fido-4t",
    searchTerms: ["aja", "fido", "fiber", "transmitter", "quad"],
    powerDrawW: 12, // typical
    heightMm: 22,
    widthMm: 117,
    depthMm: 102,
    weightKg: 0.4,
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("Fiber Out 1", "fiber", "output"),
      port("Fiber Out 2", "fiber", "output"),
      port("Fiber Out 3", "fiber", "output"),
      port("Fiber Out 4", "fiber", "output"),
    ],
  },
  // AJA FiDO-4R — Quad Fiber to SDI Receiver
  {
    id: "c0a80101-000b-4000-8000-000000000011",
    deviceType: "converter",
    label: "AJA FiDO-4R",
    manufacturer: "AJA",
    modelNumber: "FiDO-4R",
    referenceUrl: "https://www.aja.com/products/fido-4r",
    searchTerms: ["aja", "fido", "fiber", "receiver", "quad"],
    powerDrawW: 12, // typical
    heightMm: 22,
    widthMm: 117,
    depthMm: 102,
    weightKg: 0.4,
    ports: [
      port("Fiber In 1", "fiber", "input"),
      port("Fiber In 2", "fiber", "input"),
      port("Fiber In 3", "fiber", "input"),
      port("Fiber In 4", "fiber", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
    ],
  },
  // AJA FiDO-T — Single SDI to Fiber Transmitter
  {
    id: "c0a80101-000c-4000-8000-000000000012",
    deviceType: "converter",
    label: "AJA FiDO-T",
    manufacturer: "AJA",
    modelNumber: "FiDO-T",
    referenceUrl: "https://www.aja.com/products/fido-t",
    searchTerms: ["aja", "fido", "fiber", "transmitter", "single"],
    powerDrawW: 5, // typical
    heightMm: 22,
    widthMm: 117,
    depthMm: 44,
    weightKg: 0.2,
    ports: [
      port("SDI In", "sdi", "input"),
      port("Fiber Out", "fiber", "output"),
      port("SDI Loop", "sdi", "output"),
    ],
  },
  // AJA FiDO-R — Single Fiber to SDI Receiver
  {
    id: "c0a80101-000d-4000-8000-000000000013",
    deviceType: "converter",
    label: "AJA FiDO-R",
    manufacturer: "AJA",
    modelNumber: "FiDO-R",
    referenceUrl: "https://www.aja.com/products/fido-r",
    searchTerms: ["aja", "fido", "fiber", "receiver", "single"],
    powerDrawW: 5, // typical
    heightMm: 22,
    widthMm: 117,
    depthMm: 44,
    weightKg: 0.2,
    ports: [
      port("Fiber In", "fiber", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
    ],
  },
  // Datavideo DAC-70 — Cross Converter
  {
    id: "c0a80101-000e-4000-8000-000000000014",
    deviceType: "converter",
    label: "Datavideo DAC-70",
    manufacturer: "Datavideo",
    modelNumber: "DAC-70",
    referenceUrl: "https://www.datavideo.com/us/product/DAC-70",
    searchTerms: ["datavideo", "cross converter", "dac", "vga"],
    powerDrawW: 6,
    heightMm: 45,
    widthMm: 112,
    depthMm: 85,
    weightKg: 0.4,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("VGA In", "vga", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    
      port("Audio In L", "analog-audio", "input", "rca"),
    
      port("Audio In R", "analog-audio", "input", "rca"),
    ],
  },
  // Decimator MD-HX — Scaler / Cross Converter
  {
    id: "c0a80101-000f-4000-8000-000000000015",
    deviceType: "scaler",
    label: "Decimator MD-HX",
    manufacturer: "Decimator Design",
    modelNumber: "MD-HX",
    referenceUrl: "https://decimator.com/Products/MiniConverters/MD-HX/MD-HX.html",
    searchTerms: ["decimator", "cross converter", "scaler", "upconverter", "downconverter"],
    powerDrawW: 5, // typical
    heightMm: 30,
    widthMm: 123,
    depthMm: 80,
    weightKg: 0.7,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Extron DSC 301 HD — Presentation Scaler
  {
    id: "c0a80101-0010-4000-8000-000000000016",
    deviceType: "scaler",
    label: "Extron DSC 301 HD",
    manufacturer: "Extron",
    modelNumber: "DSC 301 HD",
    referenceUrl: "https://www.extron.com/product/dsc301hd",
    searchTerms: ["extron", "presentation scaler", "vga", "scan converter"],
    powerDrawW: 20, // typical
    heightMm: 25,
    widthMm: 222,
    depthMm: 152,
    weightKg: 0.6,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("VGA In", "vga", "input"),
      port("Composite In", "composite", "input"),
      port("Audio In 1", "analog-audio", "input"),
      port("Audio In 2", "analog-audio", "input"),
      port("Audio In 3", "analog-audio", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Converter
  {
    id: "c0a80101-0011-4000-8000-000000000017",
    deviceType: "converter",
    label: "Converter",
    powerDrawW: 5, // typical
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Multiviewer
  {
    id: "c0a80101-0018-4000-8000-000000000024",
    deviceType: "multiviewer",
    label: "Multiviewer",
    powerDrawW: 30, // typical
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Out", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Frame Sync
  {
    id: "c0a80101-0019-4000-8000-000000000025",
    deviceType: "frame-sync",
    label: "Frame Sync",
    powerDrawW: 15, // typical
    ports: [
      port("SDI In", "sdi", "input"),
      port("Ref In", "genlock", "input"),
      port("SDI Out", "sdi", "output"),
    
      port("AC Power", "power", "input"),
    ],
  },
  // Thunderbolt to HDMI Adapter
  {
    id: "c0a80101-001e-4000-8000-000000000030",
    deviceType: "adapter",
    label: "TB (M) → HDMI (F) Adapter",
    searchTerms: ["thunderbolt", "usb-c", "hdmi", "dongle", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("TB In", "thunderbolt", "input"), directAttach: true },
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Blackmagic UltraStudio 4K Mini
  {
    id: "c0a80101-001f-4000-8000-000000000031",
    deviceType: "converter",
    category: "converters",
    label: "BMD UltraStudio 4K Mini",
    manufacturer: "Blackmagic Design",
    modelNumber: "UltraStudio 4K Mini",
    referenceUrl: "https://www.blackmagicdesign.com/products/ultrastudio/techspecs/W-DLUS-11",
    searchTerms: ["blackmagic", "ultrastudio", "capture", "playback", "thunderbolt"],
    powerDrawW: 75,
    heightMm: 46,
    widthMm: 210,
    depthMm: 177,
    weightKg: 1.2,
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Loop", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Thunderbolt 3", "thunderbolt", "bidirectional"),
      port("RS-422", "rs422", "bidirectional"),
    
      port("Ref In", "genlock", "input"),
    
      port("Analog In", "analog-audio", "input", "trs-quarter"),
    
      port("Analog Out", "analog-audio", "output", "trs-quarter"),
    
      port("XLR Mic In", "analog-audio", "input"),
    
      port("AC Power", "power", "input", "iec"),
    ],
  },
  // ── Converters & DAs (12G upgrades + new) ────────────────────────
  {
    id: "c0a80101-0052-4000-8000-000000000082",
    deviceType: "converter",
    label: "BMD SDI→HDMI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter SDI to HDMI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters",
    searchTerms: ["blackmagic", "micro converter", "12g", "sdi to hdmi"],
    powerDrawW: 4,
    heightMm: 25,
    widthMm: 81,
    depthMm: 59,
    weightKg: 0.2,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Loop", "sdi", "output"),
    ],
  },
  {
    id: "c0a80101-0053-4000-8000-000000000083",
    deviceType: "converter",
    label: "BMD HDMI→SDI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter HDMI to SDI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters",
    searchTerms: ["blackmagic", "micro converter", "12g", "hdmi to sdi"],
    powerDrawW: 4,
    heightMm: 25,
    widthMm: 81,
    depthMm: 59,
    weightKg: 0.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
    ],
  },
  {
    id: "c0a80101-0054-4000-8000-000000000084",
    deviceType: "converter",
    label: "BMD BiDir SDI/HDMI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter BiDirectional SDI/HDMI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters",
    searchTerms: ["blackmagic", "micro converter", "bidirectional", "12g"],
    powerDrawW: 5,
    heightMm: 25,
    widthMm: 81,
    depthMm: 59,
    weightKg: 0.2,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-0057-4000-8000-000000000087",
    deviceType: "converter",
    label: "BMD Teranex SDI→HDMI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini SDI to HDMI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini",
    searchTerms: ["blackmagic", "teranex", "sdi to hdmi", "12g"],
    powerDrawW: 16,
    heightMm: 45,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Analog Out L", "analog-audio", "output"),
      port("Analog Out R", "analog-audio", "output"),
      port("AES Out", "aes", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0058-4000-8000-000000000088",
    deviceType: "converter",
    label: "BMD Teranex HDMI→SDI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini HDMI to SDI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini",
    searchTerms: ["blackmagic", "teranex", "hdmi to sdi", "12g"],
    powerDrawW: 16,
    heightMm: 45,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("SDI Monitor", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0059-4000-8000-000000000089",
    deviceType: "converter",
    label: "AJA Hi5-12G",
    manufacturer: "AJA",
    modelNumber: "Hi5-12G",
    referenceUrl: "https://www.aja.com/products/hi5-12g",
    searchTerms: ["aja", "hi5", "12g", "sdi to hdmi"],
    powerDrawW: 7, // typical
    heightMm: 23,
    widthMm: 117,
    depthMm: 102,
    weightKg: 0.3,
    ports: [
      port("12G-SDI In", "sdi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("HDMI 2.0 Out", "hdmi", "output"),

      port("Analog Out L", "analog-audio", "output", "rca"),
    
      port("Analog Out R", "analog-audio", "output", "rca"),
    ],
    slots: [
      { id: "hi5-12g-sfp-1", label: "SFP+", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
  {
    id: "c0a80101-005a-4000-8000-000000000090",
    deviceType: "converter",
    label: "AJA HA5-12G",
    manufacturer: "AJA",
    modelNumber: "HA5-12G",
    referenceUrl: "https://www.aja.com/products/ha5-12g",
    searchTerms: ["aja", "ha5", "12g", "hdmi to sdi"],
    powerDrawW: 7, // typical
    heightMm: 23,
    widthMm: 117,
    depthMm: 102,
    weightKg: 0.3,
    ports: [
      port("HDMI 2.0 In", "hdmi", "input"),
      port("12G-SDI Out 1", "sdi", "output"),
      port("12G-SDI Out 2", "sdi", "output"),

      port("Analog In L", "analog-audio", "input", "rca"),
    
      port("Analog In R", "analog-audio", "input", "rca"),
    ],
    slots: [
      { id: "ha5-12g-sfp-1", label: "SFP+", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
  {
    id: "c0a80101-005b-4000-8000-000000000091",
    deviceType: "frame-sync",
    label: "AJA FS-HDR",
    manufacturer: "AJA",
    modelNumber: "FS-HDR",
    referenceUrl: "https://www.aja.com/products/fs-hdr",
    searchTerms: ["aja", "fs-hdr", "hdr", "frame sync", "converter", "wcg"],
    powerDrawW: 40, // typical
    heightMm: 44,
    widthMm: 445,
    depthMm: 406,
    weightKg: 3.6,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      ...ports("SDI Out", "sdi", "output", 4),
      port("HDMI Monitor", "hdmi", "output"),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-005c-4000-8000-000000000092",
    deviceType: "converter",
    label: "Decimator MD-CROSS",
    manufacturer: "Decimator Design",
    modelNumber: "MD-CROSS",
    referenceUrl: "https://decimator.com/Products/MiniConverters/MD-CROSS/MD-CROSS.html",
    searchTerms: ["decimator", "cross converter", "md-cross"],
    powerDrawW: 5, // typical
    heightMm: 30,
    widthMm: 123,
    depthMm: 80,
    weightKg: 0.7,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // ── Multiviewers ─────────────────────────────────────────────────
  {
    id: "c0a80101-005d-4000-8000-000000000093",
    deviceType: "multiviewer",
    label: "BMD MultiView 4",
    manufacturer: "Blackmagic Design",
    modelNumber: "MultiView 4",
    referenceUrl: "https://www.blackmagicdesign.com/products/multiview",
    searchTerms: ["blackmagic", "multiview", "4 input", "quad"],
    powerDrawW: 16,
    heightMm: 44,
    widthMm: 140,
    depthMm: 170,
    weightKg: 0.6,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    
      port("SDI Loop 1", "sdi", "output"),
    
      port("SDI Loop 2", "sdi", "output"),
    
      port("SDI Loop 3", "sdi", "output"),
    
      port("SDI Loop 4", "sdi", "output"),
    ],
  },
  {
    id: "c0a80101-005e-4000-8000-000000000094",
    deviceType: "multiviewer",
    label: "BMD MultiView 16",
    manufacturer: "Blackmagic Design",
    modelNumber: "MultiView 16",
    referenceUrl: "https://www.blackmagicdesign.com/products/multiview",
    searchTerms: ["blackmagic", "multiview", "16 input"],
    powerDrawW: 45,
    heightMm: 44,
    widthMm: 482,
    depthMm: 153,
    weightKg: 2.1,
    ports: [
      ...ports("SDI In", "sdi", "input", 16),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    
      port("SDI MV Out 2", "sdi", "output"),
    
      port("SDI MV Out 3", "sdi", "output"),
    
      port("SDI MV Out 4", "sdi", "output"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-005f-4000-8000-000000000095",
    deviceType: "multiviewer",
    label: "Decimator DMON-QUAD",
    manufacturer: "Decimator Design",
    modelNumber: "DMON-QUAD",
    referenceUrl: "https://decimator.com/Products/MultiViewers/DMON-QUAD/DMON-QUAD.html",
    searchTerms: ["decimator", "dmon", "quad", "multiviewer"],
    powerDrawW: 7, // typical
    heightMm: 30,
    widthMm: 123,
    depthMm: 80,
    weightKg: 0.7,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      ...ports("SDI Loop", "sdi", "output", 4),
      port("SDI MV Out", "sdi", "output"),
      port("HDMI MV Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-0060-4000-8000-000000000096",
    deviceType: "multiviewer",
    label: "Decimator DMON-4S",
    manufacturer: "Decimator Design",
    modelNumber: "DMON-4S",
    referenceUrl: "https://decimator.com/Products/MultiViewers/DMON-4S/DMON-4S.html",
    searchTerms: ["decimator", "dmon", "4s", "multiviewer"],
    powerDrawW: 5, // typical
    heightMm: 30,
    widthMm: 123,
    depthMm: 80,
    weightKg: 0.7,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      ...ports("SDI Pass", "sdi", "output", 4),
      port("SDI MV Out", "sdi", "output"),
    ],
  },
  {
    id: "c0a80101-0061-4000-8000-000000000097",
    deviceType: "multiviewer",
    label: "Decimator DMON-16S",
    manufacturer: "Decimator Design",
    modelNumber: "DMON-16S",
    referenceUrl: "https://decimator.com/Products/MultiViewers/DMON-16S/DMON-16S.html",
    searchTerms: ["decimator", "dmon", "16s", "16 input", "multiviewer"],
    powerDrawW: 24, // typical
    heightMm: 30,
    widthMm: 220,
    depthMm: 104,
    ports: [
      ...ports("SDI In", "sdi", "input", 16),
      ...ports("SDI Pass", "sdi", "output", 16),
      port("SDI MV Out 1", "sdi", "output"),
      port("SDI MV Out 2", "sdi", "output"),
      port("AC Power", "power", "input"),
    
      port("HDMI MV Out", "hdmi", "output"),
    ],
  },
  // ── Capture Cards ────────────────────────────────────────────────
  {
    id: "c0a80101-006f-4000-8000-000000000111",
    deviceType: "capture-card",
    label: "BMD DeckLink SDI 4K",
    manufacturer: "Blackmagic Design",
    modelNumber: "DeckLink SDI 4K",
    referenceUrl: "https://www.blackmagicdesign.com/products/decklink",
    searchTerms: ["blackmagic", "decklink", "pcie", "capture"],
    powerDrawW: 18, // typical
    heightMm: 111,
    widthMm: 168,
    weightKg: 0.1,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out", "sdi", "output"),
    
      port("Ref In", "genlock", "input"),
    
      port("RS-422", "rs422", "bidirectional", "other"),
    ],
  },
  {
    id: "c0a80101-0070-4000-8000-000000000112",
    deviceType: "capture-card",
    label: "BMD DeckLink Duo 2",
    manufacturer: "Blackmagic Design",
    modelNumber: "DeckLink Duo 2",
    referenceUrl: "https://www.blackmagicdesign.com/products/decklink",
    searchTerms: ["blackmagic", "decklink", "duo", "pcie", "4 channel"],
    powerDrawW: 18, // typical
    heightMm: 111,
    widthMm: 168,
    weightKg: 0.2,
    ports: [
      ...ports("SDI", "sdi", "bidirectional", 4),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-0071-4000-8000-000000000113",
    deviceType: "capture-card",
    label: "BMD DeckLink Quad 2",
    manufacturer: "Blackmagic Design",
    modelNumber: "DeckLink Quad 2",
    referenceUrl: "https://www.blackmagicdesign.com/products/decklink",
    searchTerms: ["blackmagic", "decklink", "quad", "pcie", "8 channel"],
    powerDrawW: 25, // typical
    heightMm: 111,
    widthMm: 160,
    weightKg: 0.1,
    ports: [
      ...ports("SDI", "sdi", "bidirectional", 8),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-0072-4000-8000-000000000114",
    deviceType: "capture-card",
    label: "BMD UltraStudio 4K Extreme 3",
    manufacturer: "Blackmagic Design",
    modelNumber: "UltraStudio 4K Extreme 3",
    referenceUrl: "https://www.blackmagicdesign.com/products/ultrastudio",
    searchTerms: ["blackmagic", "ultrastudio", "extreme", "thunderbolt", "capture"],
    powerDrawW: 120, // typical
    heightMm: 88,
    widthMm: 482,
    depthMm: 242,
    weightKg: 3.9,
    ports: [
      port("12G-SDI In 1", "sdi", "input"),
      port("12G-SDI In 2", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("12G-SDI Out 1", "sdi", "output"),
      port("12G-SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Thunderbolt 3", "thunderbolt", "bidirectional"),
      port("Ref In", "genlock", "input"),
      port("RS-422", "rs422", "bidirectional"),
      port("Analog In", "analog-audio", "input"),
      port("Analog Out", "analog-audio", "output"),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("AC Power", "power", "input"),
    
      port("6G-SDI In 1", "sdi", "input"),
    
      port("6G-SDI In 2", "sdi", "input"),
    
      port("Thunderbolt 3 (2)", "thunderbolt", "bidirectional", "usb-c"),
    
      port("Timecode In", "genlock", "input", "xlr-3"),
    
      port("Timecode Out", "genlock", "output", "xlr-3"),
    
      port("RS-422 (2)", "rs422", "bidirectional", "other"),
    ],
  },
  // ── Generic Adapters ─────────────────────────────────────────────
  {
    id: "c0a80101-00c8-4000-8000-000000000200",
    deviceType: "adapter",
    label: "USB-C (M) → HDMI (F) Adapter",
    searchTerms: ["usb-c", "hdmi", "dongle", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("USB-C In", "usb", "input", "usb-c"), directAttach: true },
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-00c9-4000-8000-000000000201",
    deviceType: "adapter",
    label: "USB-C (M) → DP (F) Adapter",
    searchTerms: ["usb-c", "displayport", "dongle", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("USB-C In", "usb", "input", "usb-c"), directAttach: true },
      port("DP Out", "displayport", "output"),
    ],
  },
  {
    id: "c0a80101-00ca-4000-8000-000000000202",
    deviceType: "adapter",
    label: "HDMI (M) → DVI (F) Adapter",
    searchTerms: ["hdmi", "dvi", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("HDMI In", "hdmi", "input"), directAttach: true },
      port("DVI Out", "hdmi", "output", "dvi"),
    ],
  },
  {
    id: "c0a80101-00cb-4000-8000-000000000203",
    deviceType: "adapter",
    label: "Mini DP (M) → DP (F) Adapter",
    searchTerms: ["mini displayport", "displayport", "adapter", "mdp", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("Mini DP In", "displayport", "input", "other"), directAttach: true },
      port("DP Out", "displayport", "output"),
    ],
  },
  {
    id: "c0a80101-00cc-4000-8000-000000000204",
    deviceType: "adapter",
    label: "DP (M) → HDMI (F) Adapter",
    searchTerms: ["displayport", "hdmi", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("DP In", "displayport", "input"), directAttach: true },
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-00cd-4000-8000-000000000205",
    deviceType: "adapter",
    label: "BNC (F↔F) Barrel",
    searchTerms: ["bnc", "barrel", "coupler", "sdi", "adapter", "female", "gender"],
    powerDrawW: 0,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out", "sdi", "output"),
    ],
  },
  {
    // Re-ided 2026-08-18 (#300): this adapter used to share
    // c0a80101-00f8-4000-8000-000000000324 with BMD Video Assist 12G HDR 7in in
    // src/devices/recording.ts. D1 was seeded from the collided id and kept the
    // recorder, so effectiveTemplates() (dedupe by id, D1 wins) hid the adapter
    // from the Device Library.
    id: "c0a80101-030d-4000-8000-000000000735",
    deviceType: "adapter",
    label: "TB (M) → RJ45 (F) Adapter",
    searchTerms: ["thunderbolt", "usb-c", "ethernet", "dongle", "network", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("TB In", "thunderbolt", "input"), directAttach: true },
      port("Ethernet Out", "ethernet", "output"),
    ],
  },
  {
    id: "c0a80101-030c-4000-8000-000000000734",
    deviceType: "adapter",
    label: "USB-A (M) → RJ45 (F) Adapter",
    searchTerms: ["usb-a", "usb", "ethernet", "rj45", "dongle", "network", "nic", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("USB-A In", "usb", "input", "usb-a"), directAttach: true },
      port("Ethernet Out", "ethernet", "output"),
    ],
  },
  // ── Connector-Mismatch Adapters (passive cable adapters) ────────────
  // The five adapters below were re-ided 2026-08-22 (#339): each shared an id
  // with a later bundled template, and the later one wins the dedupe (D1 keeps
  // the last-seeded row), so auto-insert stamped a templateId that resolved to
  // a projector or a control device instead of the adapter it inserted.
  {
    // Was c0a80101-00ce-4000-8000-000000000206, shared with Panasonic RZ12K
    // in src/devices/projection.ts.
    id: "c0a80101-0310-4000-8000-000000000738",
    deviceType: "adapter",
    label: "USB-C (M) → USB-A (F) Adapter",
    searchTerms: ["usb-c", "usb-a", "adapter", "dongle", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("USB-C In", "usb", "input", "usb-c"), directAttach: true },
      port("USB-A Out", "usb", "output", "usb-a"),
    ],
  },
  {
    // Was c0a80101-00cf-4000-8000-000000000207, shared with D'San Perfect Cue
    // in src/devices/control.ts.
    id: "c0a80101-0311-4000-8000-000000000739",
    deviceType: "adapter",
    label: "USB-C (M) → USB-B (F) Adapter",
    searchTerms: ["usb-c", "usb-b", "adapter", "dongle", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("USB-C In", "usb", "input", "usb-c"), directAttach: true },
      port("USB-B Out", "usb", "output", "usb-b"),
    ],
  },
  {
    // Was c0a80101-00d0-4000-8000-000000000208, shared with Brainstorm SR-112
    // in src/devices/control.ts.
    id: "c0a80101-0312-4000-8000-000000000740",
    deviceType: "adapter",
    label: "mini-XLR (M) → XLR-3 (F) Adapter",
    searchTerms: ["mini-xlr", "xlr", "adapter", "audio", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("mini-XLR In", "analog-audio", "input", "mini-xlr"), directAttach: true },
      port("XLR Out", "analog-audio", "output", "xlr-3"),
    ],
  },
  {
    // Was c0a80101-00d1-4000-8000-000000000209, shared with MIDI Merge 4x2
    // in src/devices/control.ts.
    id: "c0a80101-0313-4000-8000-000000000741",
    deviceType: "adapter",
    label: "IEC (M) → Edison (F) Adapter",
    searchTerms: ["iec", "edison", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("IEC In", "power", "input", "iec"), directAttach: true },
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    // Was c0a80101-00d2-4000-8000-000000000210, shared with MIDI Thru 1x4
    // in src/devices/control.ts.
    id: "c0a80101-0314-4000-8000-000000000742",
    deviceType: "adapter",
    label: "IEC (M) → powerCON (F) Adapter",
    searchTerms: ["iec", "powercon", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("IEC In", "power", "input", "iec"), directAttach: true },
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00d3-4000-8000-000000000211",
    deviceType: "adapter",
    label: "powerCON (M) → Edison (F) Adapter",
    searchTerms: ["powercon", "edison", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("powerCON In", "power", "input", "powercon"),
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-00d4-4000-8000-000000000212",
    deviceType: "adapter",
    label: "L5-20 (M) → Edison (F) Adapter",
    searchTerms: ["l5-20", "edison", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L5-20 In", "power", "input", "l5-20"),
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-00d5-4000-8000-000000000213",
    deviceType: "adapter",
    label: "L6-20 (M) → Edison (F) Adapter",
    searchTerms: ["l6-20", "edison", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L6-20 In", "power", "input", "l6-20"),
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-00d6-4000-8000-000000000214",
    deviceType: "adapter",
    label: "L6-30 (M) → Edison (F) Adapter",
    searchTerms: ["l6-30", "edison", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L6-30 In", "power", "input", "l6-30"),
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-00d7-4000-8000-000000000215",
    deviceType: "adapter",
    label: "L5-20 (M) → powerCON (F) Adapter",
    searchTerms: ["l5-20", "powercon", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L5-20 In", "power", "input", "l5-20"),
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00d8-4000-8000-000000000216",
    deviceType: "adapter",
    label: "L6-20 (M) → powerCON (F) Adapter",
    searchTerms: ["l6-20", "powercon", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L6-20 In", "power", "input", "l6-20"),
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00d9-4000-8000-000000000217",
    deviceType: "adapter",
    label: "L6-30 (M) → powerCON (F) Adapter",
    searchTerms: ["l6-30", "powercon", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L6-30 In", "power", "input", "l6-30"),
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00da-4000-8000-000000000218",
    deviceType: "adapter",
    label: "L21-30 (M) → Edison (F) Adapter",
    searchTerms: ["l21-30", "edison", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L21-30 In", "power", "input", "l21-30"),
      port("Edison Out", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-00db-4000-8000-000000000219",
    deviceType: "adapter",
    label: "L21-30 (M) → powerCON (F) Adapter",
    searchTerms: ["l21-30", "powercon", "power", "adapter", "twist-lock", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("L21-30 In", "power", "input", "l21-30"),
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  // ── Barrels / Couplers ─────────────────────────────────────────────
  {
    id: "c0a80101-00dc-4000-8000-000000000220",
    deviceType: "adapter",
    label: "HDMI (F↔F) Barrel",
    searchTerms: ["hdmi", "barrel", "coupler", "adapter", "female", "gender"],
    powerDrawW: 0,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-00dd-4000-8000-000000000221",
    deviceType: "adapter",
    label: "VGA (F↔F) Barrel",
    searchTerms: ["vga", "barrel", "coupler", "adapter", "female", "gender"],
    powerDrawW: 0,
    ports: [
      port("VGA In", "vga", "input"),
      port("VGA Out", "vga", "output"),
    ],
  },
  {
    id: "c0a80101-00de-4000-8000-000000000222",
    deviceType: "adapter",
    label: "XLR-3 (F↔F) Barrel",
    searchTerms: ["xlr", "barrel", "coupler", "adapter", "female", "gender", "audio"],
    powerDrawW: 0,
    ports: [
      port("XLR In", "analog-audio", "input", "xlr-3"),
      port("XLR Out", "analog-audio", "output", "xlr-3"),
    ],
  },
  {
    id: "c0a80101-00df-4000-8000-000000000223",
    deviceType: "adapter",
    label: "XLR-5 (F↔F) Barrel",
    searchTerms: ["xlr-5", "barrel", "coupler", "adapter", "female", "gender", "dmx"],
    powerDrawW: 0,
    ports: [
      port("XLR-5 In", "dmx", "input"),
      port("XLR-5 Out", "dmx", "output"),
    ],
  },
  {
    id: "c0a80101-00e0-4000-8000-000000000224",
    deviceType: "adapter",
    label: 'TRS 1/4" (F↔F) Barrel',
    searchTerms: ["trs", "quarter", "barrel", "coupler", "adapter", "female", "gender", "audio"],
    powerDrawW: 0,
    ports: [
      port("TRS In", "analog-audio", "input", "trs-quarter"),
      port("TRS Out", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-00e1-4000-8000-000000000225",
    deviceType: "adapter",
    label: "RJ45 (F↔F) Coupler",
    searchTerms: ["rj45", "coupler", "barrel", "adapter", "female", "gender", "ethernet", "network"],
    powerDrawW: 0,
    ports: [
      port("RJ45 In", "ethernet", "input", "rj45"),
      port("RJ45 Out", "ethernet", "output", "rj45"),
    ],
  },
  {
    id: "c0a80101-00e2-4000-8000-000000000226",
    deviceType: "adapter",
    label: "RCA (F↔F) Barrel",
    searchTerms: ["rca", "barrel", "coupler", "adapter", "female", "gender", "spdif"],
    powerDrawW: 0,
    ports: [
      port("RCA In", "spdif", "input", "rca"),
      port("RCA Out", "spdif", "output", "rca"),
    ],
  },
  {
    id: "c0a80101-00e3-4000-8000-000000000227",
    deviceType: "adapter",
    label: "TOSLINK (F↔F) Barrel",
    searchTerms: ["toslink", "barrel", "coupler", "adapter", "female", "gender", "adat", "optical"],
    powerDrawW: 0,
    ports: [
      port("TOSLINK In", "adat", "input", "toslink"),
      port("TOSLINK Out", "adat", "output", "toslink"),
    ],
  },
  {
    id: "c0a80101-00e4-4000-8000-000000000228",
    deviceType: "adapter",
    label: "speakON (F↔F) Barrel",
    searchTerms: ["speakon", "barrel", "coupler", "adapter", "female", "gender", "speaker"],
    powerDrawW: 0,
    ports: [
      port("speakON In", "speaker-level", "input", "speakon"),
      port("speakON Out", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00e5-4000-8000-000000000229",
    deviceType: "adapter",
    label: "DB9 (F↔F) Barrel",
    searchTerms: ["db9", "barrel", "coupler", "adapter", "female", "gender", "serial", "rs422"],
    powerDrawW: 0,
    ports: [
      port("DB9 In", "rs422", "input", "db9"),
      port("DB9 Out", "rs422", "output", "db9"),
    ],
  },
  {
    id: "c0a80101-00e6-4000-8000-000000000230",
    deviceType: "adapter",
    label: "USB-A (F↔F) Barrel",
    searchTerms: ["usb-a", "barrel", "coupler", "adapter", "female", "gender"],
    powerDrawW: 0,
    ports: [
      port("USB-A In", "usb", "input", "usb-a"),
      port("USB-A Out", "usb", "output", "usb-a"),
    ],
  },
  // ── Reverse Power Adapters ─────────────────────────────────────────
  {
    id: "c0a80101-00e7-4000-8000-000000000231",
    deviceType: "adapter",
    label: "Edison (M) → IEC (F) Adapter",
    searchTerms: ["edison", "iec", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("IEC Out", "power", "output", "iec"),
    ],
  },
  {
    id: "c0a80101-00e8-4000-8000-000000000232",
    deviceType: "adapter",
    label: "Edison (M) → powerCON (F) Adapter",
    searchTerms: ["edison", "powercon", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("powerCON Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00e9-4000-8000-000000000233",
    deviceType: "adapter",
    label: "Edison (M) → L5-20 (F) Adapter",
    searchTerms: ["edison", "l5-20", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("L5-20 Out", "power", "output", "l5-20"),
    ],
  },
  {
    id: "c0a80101-00ea-4000-8000-000000000234",
    deviceType: "adapter",
    label: "Edison (M) → L6-20 (F) Adapter",
    searchTerms: ["edison", "l6-20", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("L6-20 Out", "power", "output", "l6-20"),
    ],
  },
  {
    id: "c0a80101-00eb-4000-8000-000000000235",
    deviceType: "adapter",
    label: "Edison (M) → L6-30 (F) Adapter",
    searchTerms: ["edison", "l6-30", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("L6-30 Out", "power", "output", "l6-30"),
    ],
  },
  {
    id: "c0a80101-00ec-4000-8000-000000000236",
    deviceType: "adapter",
    label: "Edison (M) → L21-30 (F) Adapter",
    searchTerms: ["edison", "l21-30", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("Edison In", "power", "input", "edison"),
      port("L21-30 Out", "power", "output", "l21-30"),
    ],
  },
  {
    id: "c0a80101-00ed-4000-8000-000000000237",
    deviceType: "adapter",
    label: "powerCON (M) → IEC (F) Adapter",
    searchTerms: ["powercon", "iec", "power", "adapter", "cable", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("powerCON In", "power", "input", "powercon"),
      port("IEC Out", "power", "output", "iec"),
    ],
  },
  {
    id: "c0a80101-00ee-4000-8000-000000000238",
    deviceType: "adapter",
    label: "powerCON (M) → L5-20 (F) Adapter",
    searchTerms: ["powercon", "l5-20", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("powerCON In", "power", "input", "powercon"),
      port("L5-20 Out", "power", "output", "l5-20"),
    ],
  },
  {
    id: "c0a80101-00ef-4000-8000-000000000239",
    deviceType: "adapter",
    label: "powerCON (M) → L6-20 (F) Adapter",
    searchTerms: ["powercon", "l6-20", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("powerCON In", "power", "input", "powercon"),
      port("L6-20 Out", "power", "output", "l6-20"),
    ],
  },
  {
    id: "c0a80101-00f0-4000-8000-000000000240",
    deviceType: "adapter",
    label: "powerCON (M) → L6-30 (F) Adapter",
    searchTerms: ["powercon", "l6-30", "power", "adapter", "cable", "male", "female", "twist-lock"],
    powerDrawW: 0,
    ports: [
      port("powerCON In", "power", "input", "powercon"),
      port("L6-30 Out", "power", "output", "l6-30"),
    ],
  },
  // ── Audio Adapters ─────────────────────────────────────────────────
  {
    id: "c0a80101-00f1-4000-8000-000000000241",
    deviceType: "adapter",
    label: "XLR-3 (M) → TRS 1/4\" (F) Adapter",
    searchTerms: ["xlr", "trs", "quarter", "adapter", "audio", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("XLR In", "analog-audio", "input", "xlr-3"),
      port("TRS Out", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-00f2-4000-8000-000000000242",
    deviceType: "adapter",
    label: "TRS 1/4\" (M) → XLR-3 (F) Adapter",
    searchTerms: ["trs", "quarter", "xlr", "adapter", "audio", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("TRS In", "analog-audio", "input", "trs-quarter"),
      port("XLR Out", "analog-audio", "output", "xlr-3"),
    ],
  },
  {
    id: "c0a80101-00f3-4000-8000-000000000243",
    deviceType: "adapter",
    label: "TRS 1/8\" (M) → TRS 1/4\" (F) Adapter",
    searchTerms: ["trs", "eighth", "quarter", "adapter", "audio", "male", "female", "3.5mm"],
    powerDrawW: 0,
    ports: [
      port("TRS 1/8 In", "analog-audio", "input", "trs-eighth"),
      port("TRS 1/4 Out", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-00f4-4000-8000-000000000244",
    deviceType: "adapter",
    label: "TRS 1/4\" (M) → TRS 1/8\" (F) Adapter",
    searchTerms: ["trs", "quarter", "eighth", "adapter", "audio", "male", "female", "3.5mm"],
    powerDrawW: 0,
    ports: [
      port("TRS 1/4 In", "analog-audio", "input", "trs-quarter"),
      port("TRS 1/8 Out", "analog-audio", "output", "trs-eighth"),
    ],
  },
  {
    id: "c0a80101-00f5-4000-8000-000000000245",
    deviceType: "adapter",
    label: "XLR-3 (M) → RCA (F) Adapter",
    searchTerms: ["xlr", "rca", "adapter", "audio", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("XLR In", "analog-audio", "input", "xlr-3"),
      port("RCA Out", "analog-audio", "output", "rca"),
    ],
  },
  {
    id: "c0a80101-00f6-4000-8000-000000000246",
    deviceType: "adapter",
    label: "RCA (M) → XLR-3 (F) Adapter",
    searchTerms: ["rca", "xlr", "adapter", "audio", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("RCA In", "analog-audio", "input", "rca"),
      port("XLR Out", "analog-audio", "output", "xlr-3"),
    ],
  },
  // ── Video Adapters ─────────────────────────────────────────────────
  {
    id: "c0a80101-00f7-4000-8000-000000000247",
    deviceType: "adapter",
    label: "Mini DP (M) → HDMI (F) Adapter",
    searchTerms: ["mini displayport", "hdmi", "adapter", "mdp", "male", "female"],
    powerDrawW: 0,
    ports: [
      { ...port("Mini DP In", "displayport", "input", "other"), directAttach: true },
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-0100-4000-8000-000000000248",
    deviceType: "adapter",
    label: "DVI (M) → HDMI (F) Adapter",
    searchTerms: ["dvi", "hdmi", "adapter", "male", "female"],
    powerDrawW: 0,
    ports: [
      port("DVI In", "hdmi", "input", "dvi"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-00fe-4000-8000-000000000330",
    deviceType: "converter",
    category: "converters",
    label: "BMD Mini Converter Optical Fiber 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Mini Converter Optical Fiber 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/miniconverters",
    searchTerms: ["blackmagic", "mini converter", "optical", "fiber", "12g", "sdi"],
    powerDrawW: 2,
    heightMm: 23,
    widthMm: 122,
    depthMm: 92,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out", "sdi", "output"),
      port("Fiber In", "fiber", "input"),
      port("Fiber Out", "fiber", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0194-4000-8000-000000000404",
    deviceType: "converter",
    category: "converters",
    label: "Decimator 12G-Cross",
    manufacturer: "Decimator Design",
    modelNumber: "12G-CROSS",
    referenceUrl: "https://decimator.com/Products/MiniConverters/12G-CROSS/12G-CROSS.html",
    searchTerms: ["decimator", "12g", "cross converter", "4k", "scaler"],
    powerDrawW: 7, // typical
    heightMm: 31,
    widthMm: 130,
    depthMm: 106,
    weightKg: 0.5,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("SDI Loop 1", "sdi", "output"),
      port("SDI Loop 2", "sdi", "output"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  {
    id: "c0a80101-0195-4000-8000-000000000405",
    deviceType: "converter",
    category: "converters",
    label: "BMD Studio Fiber Converter",
    manufacturer: "Blackmagic Design",
    modelNumber: "Studio Fiber Converter",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicfiberconverters",
    searchTerms: ["blackmagic", "studio fiber", "smpte", "fiber converter", "camera"],
    powerDrawW: 60, // typical
    heightMm: 88,
    widthMm: 210,
    depthMm: 372,
    weightKg: 2.8,
    ports: [
      ...ports("12G-SDI In", "sdi", "input", 3),
      ...ports("12G-SDI Out", "sdi", "output", 2),
      port("SMPTE Fiber", "fiber", "bidirectional", "other"),
      ...ports("XLR Out", "analog-audio", "output", 4),
      port("Talkback 1", "analog-audio", "bidirectional", "xlr-5"),
      port("Talkback 2", "analog-audio", "bidirectional", "xlr-5"),
      port("Ref In", "genlock", "input"),
      port("Ref Out", "genlock", "output"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-024c-4000-8000-000000000733",
    deviceType: "capture-card",
    label: "Magewell USB Capture SDI Gen 2",
    manufacturer: "Magewell",
    modelNumber: "USB Capture SDI Gen 2",
    referenceUrl: "https://www.magewell.com/products/usb-capture-sdi-gen-2",
    searchTerms: ["magewell", "usb capture", "sdi", "gen 2", "3g-sdi", "dongle"],
    powerDrawW: 2.5, // USB bus-powered
    heightMm: 12.3,
    widthMm: 40.2,
    depthMm: 92.2,
    ports: [
      port("3G-SDI In", "sdi", "input"),
      port("USB 3.0", "usb", "output"),
    ],
  },
];
