import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Panasonic PT-DZ13K — Large Venue Projector
  {
    id: "c0a80101-0022-4000-8000-000000000034",
    deviceType: "projector",
    label: "Panasonic DZ13K",
    manufacturer: "Panasonic",
    modelNumber: "PT-DZ13K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-dz13ku-3-chip-dlptm-large-venue-projector",
    powerDrawW: 1000,
    heightMm: 200,
    widthMm: 530,
    depthMm: 549,
    weightKg: 24,
    ports: [
      port("RGBHV In (BNC)", "vga", "input"),
      port("RGB In (VGA)", "vga", "input"),
      port("DVI-D In", "hdmi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2 (3G)", "sdi", "input"),
      port("Composite In", "composite", "input"),
      port("RS-232 In", "serial", "input"),
      port("LAN", "ethernet", "bidirectional"),
      port("RS-232 Out", "serial", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Panasonic PT-RZ21K — Large Venue Laser Projector
  {
    id: "c0a80101-0023-4000-8000-000000000035",
    deviceType: "projector",
    label: "Panasonic RZ21K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RZ21K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-rz21ku-3-chip-dlptm-solid-shine-laser-projector",
    searchTerms: ["panasonic", "laser", "dlp", "21k", "projector"],
    powerDrawW: 1510,
    heightMm: 270,
    widthMm: 598,
    depthMm: 725,
    weightKg: 49,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("RGB BNC In", "vga", "input"),
      port("RS-232 In", "serial", "input"),
      port("LAN", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Projectors ───────────────────────────────────────────────────
  {
    id: "c0a80101-00ce-4000-8000-000000000206",
    deviceType: "projector",
    label: "Panasonic RZ12K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RZ12K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-rz12ku",
    searchTerms: ["panasonic", "laser", "12k lumens", "projector"],
    powerDrawW: 1200,
    heightMm: 323,
    widthMm: 579,
    depthMm: 739,
    weightKg: 44,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("RS-232", "serial", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0189-4000-8000-000000000393",
    deviceType: "projector",
    category: "projectors",
    label: "Barco HDX-W20 Flex",
    manufacturer: "Barco",
    modelNumber: "HDX-W20 Flex",
    referenceUrl: "https://www.barco.com/en/support/hdx-w20-flex",
    searchTerms: ["barco", "hdx", "w20", "flex", "20000 lumens", "projector", "dlp"],
    powerDrawW: 2200, // typical
    heightMm: 382,
    widthMm: 475,
    depthMm: 725,
    weightKg: 49.9,
    ports: [
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("VGA In (5-BNC)", "vga", "input", "bnc"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018a-4000-8000-000000000394",
    deviceType: "projector",
    category: "projectors",
    label: "Barco UDX-4K32",
    manufacturer: "Barco",
    modelNumber: "UDX-4K32",
    referenceUrl: "https://www.barco.com/en/product/udx-4k32",
    searchTerms: ["barco", "udx", "4k32", "31000 lumens", "4k", "projector", "laser"],
    powerDrawW: 3100,
    heightMm: 350,
    widthMm: 660,
    depthMm: 830,
    weightKg: 92,
    ports: [
      port("HDMI 2.0 In", "hdmi", "input"),
      port("DP 1.2 In", "displayport", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      ...ports("SDI In", "sdi", "input", 4),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018b-4000-8000-000000000395",
    deviceType: "projector",
    category: "projectors",
    label: "Barco UDM-W22",
    manufacturer: "Barco",
    modelNumber: "UDM-W22",
    referenceUrl: "https://www.barco.com/en/product/udm-w22",
    searchTerms: ["barco", "udm", "w22", "22000 lumens", "wuxga", "projector", "laser"],
    powerDrawW: 2400,
    heightMm: 339,
    widthMm: 725,
    depthMm: 540,
    weightKg: 48,
    ports: [
      port("HDMI 2.0 In", "hdmi", "input"),
      port("DP 1.2 In", "displayport", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      ...ports("SDI In", "sdi", "input", 4),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018c-4000-8000-000000000396",
    deviceType: "projector",
    category: "projectors",
    label: "Barco UDM-4K22",
    manufacturer: "Barco",
    modelNumber: "UDM-4K22",
    referenceUrl: "https://www.barco.com/en/product/udm-4k22",
    searchTerms: ["barco", "udm", "4k22", "22000 lumens", "4k", "projector", "laser"],
    powerDrawW: 2400,
    heightMm: 339,
    widthMm: 725,
    depthMm: 540,
    weightKg: 48,
    ports: [
      port("HDMI 2.0 In", "hdmi", "input"),
      port("DP 1.2 In", "displayport", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      ...ports("SDI In", "sdi", "input", 4),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018d-4000-8000-000000000397",
    deviceType: "projector",
    category: "projectors",
    label: "Panasonic PT-RZ34K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RZ34K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-rz34ku-3-chip-dlptm-wuxga-large-venue-laser-projector",
    searchTerms: ["panasonic", "rz34k", "30500 lumens", "wuxga", "projector", "laser"],
    powerDrawW: 2450,
    heightMm: 353,
    widthMm: 598,
    depthMm: 780,
    weightKg: 68.6,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("SDI In", "sdi", "input"),
      port("DIGITAL LINK In", "hdbaset", "input"),
      port("Serial In", "serial", "input", "db9"),
      port("Serial Out", "serial", "output", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018e-4000-8000-000000000398",
    deviceType: "projector",
    category: "projectors",
    label: "Panasonic PT-RQ25K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RQ25K",
    referenceUrl: "https://eu.connect.panasonic.com/gb/en/projectors/pt-rq25k-series/pt-rq25k",
    searchTerms: ["panasonic", "rq25k", "21000 lumens", "4k", "projector", "laser"],
    powerDrawW: 1520,
    heightMm: 221,
    widthMm: 551,
    depthMm: 569,
    weightKg: 35,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("Serial In", "serial", "input", "db9"),
      port("Serial Out", "serial", "output", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-018f-4000-8000-000000000399",
    deviceType: "projector",
    category: "projectors",
    label: "Panasonic PT-RQ35K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RQ35K",
    referenceUrl: "https://eu.connect.panasonic.com/gb/en/products/projectors/pt-rq35k",
    searchTerms: ["panasonic", "rq35k", "30500 lumens", "4k", "projector", "laser"],
    powerDrawW: 2550,
    heightMm: 361,
    widthMm: 599,
    depthMm: 800,
    weightKg: 69.8,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("SDI In", "sdi", "input"),
      port("DIGITAL LINK In", "hdbaset", "input"),
      port("Serial In", "serial", "input", "db9"),
      port("Serial Out", "serial", "output", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0190-4000-8000-000000000400",
    deviceType: "projector",
    category: "projectors",
    label: "Epson EB-PU2220B",
    manufacturer: "Epson",
    modelNumber: "EB-PU2220B",
    referenceUrl: "https://epson.com/For-Work/Projectors/Large-Venue/EB-PU2220B-20,000-Lumen-3LCD-Large-Venue-Laser-Projector-with-4K-Enhancement/p/V11HA66820",
    searchTerms: ["epson", "pu2220b", "20000 lumens", "wuxga", "projector", "laser"],
    powerDrawW: 1301,
    heightMm: 218,
    widthMm: 587,
    depthMm: 493,
    weightKg: 24.4,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("3G-SDI In", "sdi", "input"),
      port("3G-SDI Out", "sdi", "output"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0191-4000-8000-000000000401",
    deviceType: "projector",
    category: "projectors",
    label: "Epson Pro L1755U",
    manufacturer: "Epson",
    modelNumber: "Pro L1755U",
    referenceUrl: "https://epson.com/For-Work/Projectors/Large-Venue/Pro-L1755UNL-WUXGA-3LCD-Laser-Projector-with-4K-Enhancement-Without-Lens/p/V11H892820",
    searchTerms: ["epson", "l1755u", "15000 lumens", "wuxga", "projector", "laser"],
    powerDrawW: 1082,
    heightMm: 211,
    widthMm: 586,
    depthMm: 492,
    weightKg: 24.1,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("3G-SDI In", "sdi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("VGA In (5-BNC)", "vga", "input", "bnc"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0247-4000-8000-000000000728",
    deviceType: "projector",
    category: "projectors",
    label: "Epson Pro L1505U",
    manufacturer: "Epson",
    modelNumber: "Pro L1505U",
    referenceUrl: "https://epson.com/For-Work/Projectors/Large-Venue/Pro-L1505U-Laser-WUXGA-3LCD-Projector-with-4K-Enhancement-&-Standard-Lens/p/V11H792120",
    searchTerms: ["epson", "l1505u", "12000 lumens", "wuxga", "projector", "laser"],
    powerDrawW: 955,
    heightMm: 211,
    widthMm: 587,
    depthMm: 493,
    weightKg: 21.7,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("3G-SDI In", "sdi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In (5-BNC)", "vga", "input", "bnc"),
      port("Monitor Out (VGA)", "vga", "output"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0248-4000-8000-000000000729",
    deviceType: "projector",
    category: "projectors",
    label: "Epson EB-PU2216B",
    manufacturer: "Epson",
    modelNumber: "EB-PU2216B",
    referenceUrl: "https://epson.com/For-Work/Projectors/Large-Venue/EB-PU2216B-16,000-Lumen-3LCD-Large-Venue-Laser-Projector-with-4K-Enhancement/p/V11HA67820",
    searchTerms: ["epson", "pu2216b", "16000 lumens", "wuxga", "projector", "laser", "black"],
    powerDrawW: 1118,
    heightMm: 185,
    widthMm: 586,
    depthMm: 492,
    weightKg: 24.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("3G-SDI In", "sdi", "input"),
      port("3G-SDI Out", "sdi", "output"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
];
