import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Speakers & Amplifiers ────────────────────────────────────────
  {
    id: "c0a80101-00a7-4000-8000-000000000167",
    deviceType: "speaker",
    label: "Meyer Leopard",
    manufacturer: "Meyer Sound",
    modelNumber: "Leopard",
    referenceUrl: "https://meyersound.com/product/leopard/",
    searchTerms: ["meyer", "leopard", "line array", "powered"],
    powerDrawW: 450, // typical
    heightMm: 282,
    widthMm: 684,
    depthMm: 550,
    weightKg: 34,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00a8-4000-8000-000000000168",
    deviceType: "speaker",
    label: "L'Acoustics KIVA II",
    manufacturer: "L'Acoustics",
    modelNumber: "KIVA II",
    referenceUrl: "https://www.l-acoustics.com/products/kiva-ii/",
    searchTerms: ["l-acoustics", "kiva", "line array", "passive"],
    powerDrawW: 0,
    heightMm: 202,
    widthMm: 525,
    depthMm: 357,
    weightKg: 14,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00a9-4000-8000-000000000169",
    deviceType: "speaker",
    label: "JBL VRX928LA",
    manufacturer: "JBL Professional",
    modelNumber: "VRX928LA",
    referenceUrl: "https://jblpro.com/products/vrx928la",
    searchTerms: ["jbl", "vrx", "line array", "passive", "compact"],
    powerDrawW: 0,
    heightMm: 230,
    widthMm: 420,
    depthMm: 270,
    weightKg: 12.7,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00aa-4000-8000-000000000170",
    deviceType: "speaker",
    label: "Meyer UPM-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPM-1P",
    referenceUrl: "https://meyersound.com/product/upm-1p/",
    searchTerms: ["meyer", "upm", "powered", "fill", "delay"],
    powerDrawW: 200, // typical
    heightMm: 457,
    widthMm: 176,
    depthMm: 193,
    weightKg: 10,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ab-4000-8000-000000000171",
    deviceType: "speaker",
    label: "Meyer UPA-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPA-1P",
    referenceUrl: "https://meyersound.com/product/upa-1p/",
    searchTerms: ["meyer", "upa", "powered", "loudspeaker"],
    powerDrawW: 400, // typical
    heightMm: 569,
    widthMm: 368,
    depthMm: 363,
    weightKg: 34.9,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ac-4000-8000-000000000172",
    deviceType: "speaker",
    label: "QSC K12.2",
    manufacturer: "QSC",
    modelNumber: "K12.2",
    referenceUrl: "https://www.qsc.com/products-solutions/loudspeakers/powered-loudspeakers/k2-series/k122/",
    searchTerms: ["qsc", "k12", "k series", "powered", "portable"],
    powerDrawW: 200, // typical
    heightMm: 602,
    widthMm: 356,
    depthMm: 351,
    weightKg: 17.7,
    ports: [
      port("Combo In 1", "analog-audio", "input", "combo-xlr-trs"),
      port("Combo In 2", "analog-audio", "input", "combo-xlr-trs"),
      port("Line Out", "analog-audio", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00ad-4000-8000-000000000173",
    deviceType: "speaker",
    label: "Meyer 900-LFC",
    manufacturer: "Meyer Sound",
    modelNumber: "900-LFC",
    referenceUrl: "https://meyersound.com/product/900-lfc/",
    searchTerms: ["meyer", "900", "lfc", "subwoofer", "powered"],
    powerDrawW: 1100, // typical
    heightMm: 621,
    widthMm: 697,
    depthMm: 632,
    weightKg: 61.7,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ae-4000-8000-000000000174",
    deviceType: "speaker",
    label: "L'Acoustics SB15m",
    manufacturer: "L'Acoustics",
    modelNumber: "SB15m",
    referenceUrl: "https://www.l-acoustics.com/products/sb15m/",
    searchTerms: ["l-acoustics", "sb15", "subwoofer", "passive"],
    powerDrawW: 0,
    heightMm: 493,
    widthMm: 579,
    depthMm: 520,
    weightKg: 36,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00af-4000-8000-000000000175",
    deviceType: "speaker",
    label: "Meyer MJF-210",
    manufacturer: "Meyer Sound",
    modelNumber: "MJF-210",
    referenceUrl: "https://meyersound.com/product/mjf-210/",
    searchTerms: ["meyer", "mjf", "wedge", "monitor", "stage"],
    powerDrawW: 200, // typical
    heightMm: 353,
    widthMm: 589,
    depthMm: 531,
    weightKg: 30.4,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00b0-4000-8000-000000000176",
    deviceType: "amplifier",
    label: "QSC PLD 4.5",
    manufacturer: "QSC",
    modelNumber: "PLD 4.5",
    referenceUrl: "https://www.qsc.com/products-solutions/power-amplifiers/installed/pld-series/pld-4-5/",
    searchTerms: ["qsc", "pld", "amplifier", "dsp", "4 channel"],
    powerDrawW: 1800, // typical
    heightMm: 89,
    widthMm: 482,
    depthMm: 406,
    weightKg: 10,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      ...ports("Speaker Out", "speaker-level", "output", 4, "speakon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00b1-4000-8000-000000000177",
    deviceType: "amplifier",
    label: "L'Acoustics LA4X",
    manufacturer: "L'Acoustics",
    modelNumber: "LA4X",
    referenceUrl: "https://www.l-acoustics.com/products/la4x/",
    searchTerms: ["l-acoustics", "la4x", "amplified controller", "4 channel"],
    powerDrawW: 1800, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 398,
    weightKg: 11.3,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4),
      ...ports("Speaker Out", "speaker-level", "output", 4, "speakon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),

      port("AES In 1-2", "aes", "input"),
    
      port("AES In 3-4", "aes", "input"),
    
      port("AES Link 1-2", "aes", "output"),
    ],
  },

  // ── L-Acoustics Speakers ───────────────────────────────────────────
  {
    id: "c0a80101-01c3-4000-8000-000000000451",
    deviceType: "speaker",
    label: "L'Acoustics A15 Wide",
    manufacturer: "L'Acoustics",
    modelNumber: "A15 Wide",
    referenceUrl: "https://www.l-acoustics.com/products/a15-wide/",
    searchTerms: ["l-acoustics", "a15", "wide", "line array", "passive", "a series"],
    powerDrawW: 0,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c4-4000-8000-000000000452",
    deviceType: "speaker",
    label: "L'Acoustics K3",
    manufacturer: "L'Acoustics",
    modelNumber: "K3",
    referenceUrl: "https://www.l-acoustics.com/products/k3/",
    searchTerms: ["l-acoustics", "k3", "line array", "passive", "k series"],
    powerDrawW: 0,
    heightMm: 355,
    widthMm: 950,
    depthMm: 402,
    weightKg: 43,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c5-4000-8000-000000000453",
    deviceType: "speaker",
    label: "L'Acoustics SYVA",
    manufacturer: "L'Acoustics",
    modelNumber: "SYVA",
    referenceUrl: "https://www.l-acoustics.com/products/syva/",
    searchTerms: ["l-acoustics", "syva", "column", "passive", "segment source"],
    powerDrawW: 0,
    heightMm: 1304,
    widthMm: 144,
    depthMm: 208,
    weightKg: 21,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c6-4000-8000-000000000454",
    deviceType: "speaker",
    label: "L'Acoustics X15 HiQ",
    manufacturer: "L'Acoustics",
    modelNumber: "X15 HiQ",
    referenceUrl: "https://www.l-acoustics.com/products/x15-hiq/",
    searchTerms: ["l-acoustics", "x15", "hiq", "coaxial", "stage monitor", "passive"],
    powerDrawW: 0,
    heightMm: 375,
    widthMm: 430,
    depthMm: 471,
    weightKg: 21,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c7-4000-8000-000000000455",
    deviceType: "speaker",
    label: "L'Acoustics X8",
    manufacturer: "L'Acoustics",
    modelNumber: "X8",
    referenceUrl: "https://www.l-acoustics.com/products/x8/",
    searchTerms: ["l-acoustics", "x8", "coaxial", "passive", "compact"],
    powerDrawW: 0,
    heightMm: 249,
    widthMm: 424,
    depthMm: 305,
    weightKg: 12,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c8-4000-8000-000000000456",
    deviceType: "speaker",
    label: "L'Acoustics X12",
    manufacturer: "L'Acoustics",
    modelNumber: "X12",
    referenceUrl: "https://www.l-acoustics.com/products/x12/",
    searchTerms: ["l-acoustics", "x12", "coaxial", "passive", "point source"],
    powerDrawW: 0,
    heightMm: 430,
    widthMm: 496,
    depthMm: 471,
    weightKg: 20,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01c9-4000-8000-000000000457",
    deviceType: "speaker",
    label: "L'Acoustics KS28",
    manufacturer: "L'Acoustics",
    modelNumber: "KS28",
    referenceUrl: "https://www.l-acoustics.com/products/ks28/",
    searchTerms: ["l-acoustics", "ks28", "subwoofer", "passive", "k series"],
    powerDrawW: 0,
    heightMm: 719,
    widthMm: 1340,
    depthMm: 565,
    weightKg: 79,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
    ],
  },
  {
    id: "c0a80101-01ca-4000-8000-000000000458",
    deviceType: "speaker",
    label: "L'Acoustics K2",
    manufacturer: "L'Acoustics",
    modelNumber: "K2",
    referenceUrl: "https://www.l-acoustics.com/products/k2/",
    searchTerms: ["l-acoustics", "k2", "line array", "passive", "k series"],
    powerDrawW: 0,
    heightMm: 350,
    widthMm: 1350,
    depthMm: 520,
    weightKg: 56,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01cb-4000-8000-000000000459",
    deviceType: "speaker",
    label: "L'Acoustics Kara II",
    manufacturer: "L'Acoustics",
    modelNumber: "Kara II",
    referenceUrl: "https://www.l-acoustics.com/products/kara-ii/",
    searchTerms: ["l-acoustics", "kara", "line array", "passive", "k series"],
    powerDrawW: 0,
    heightMm: 287,
    widthMm: 733,
    depthMm: 383,
    weightKg: 26,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01cc-4000-8000-000000000460",
    deviceType: "speaker",
    label: "L'Acoustics 5XT",
    manufacturer: "L'Acoustics",
    modelNumber: "5XT",
    referenceUrl: "https://www.l-acoustics.com/products/5xt/",
    searchTerms: ["l-acoustics", "5xt", "coaxial", "passive", "ultra-compact"],
    powerDrawW: 0,
    heightMm: 165,
    widthMm: 165,
    depthMm: 165,
    weightKg: 3.5,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01cd-4000-8000-000000000461",
    deviceType: "speaker",
    label: "L'Acoustics SB18",
    manufacturer: "L'Acoustics",
    modelNumber: "SB18",
    referenceUrl: "https://www.l-acoustics.com/products/sb18/",
    searchTerms: ["l-acoustics", "sb18", "subwoofer", "passive"],
    powerDrawW: 0,
    heightMm: 707,
    widthMm: 750,
    depthMm: 540,
    weightKg: 52,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },

  // ── L-Acoustics Amplified Controllers ──────────────────────────────
  {
    id: "c0a80101-01ce-4000-8000-000000000462",
    deviceType: "amplifier",
    label: "L'Acoustics LA7.16",
    manufacturer: "L'Acoustics",
    modelNumber: "LA7.16",
    referenceUrl: "https://www.l-acoustics.com/products/la7-16/",
    searchTerms: ["l-acoustics", "la7", "amplified controller", "16 channel", "milan", "avb"],
    powerDrawW: 3700, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 510,
    weightKg: 15.8,
    ports: [
      port("Analog In", "analog-audio", "input"),
      port("AES In 1-2", "aes", "input"),
      port("AVB Primary", "avb", "bidirectional", "ethercon"),
      port("AVB Secondary", "avb", "bidirectional", "ethercon"),
      port("Speaker Out", "analog-audio", "output", "multipin"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01cf-4000-8000-000000000463",
    deviceType: "amplifier",
    label: "L'Acoustics LA-RAK II",
    manufacturer: "L'Acoustics",
    modelNumber: "LA-RAK II AVB",
    referenceUrl: "https://www.l-acoustics.com/products/la-rak-ii-avb/",
    searchTerms: ["l-acoustics", "la-rak", "rack", "amplified controller", "touring", "avb", "milan"],
    powerDrawW: 5400, // typical (3x LA4X)
    ports: [
      ...ports("Analog In", "analog-audio", "input", 6),
      port("AES In 1-2", "aes", "input"),
      port("AES In 3-4", "aes", "input"),
      port("AES In 5-6", "aes", "input"),
      ...ports("Speaker Out", "speaker-level", "output", 12, "speakon"),
      port("AVB Primary", "avb", "bidirectional", "ethercon"),
      port("AVB Secondary", "avb", "bidirectional", "ethercon"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("AC Power", "power", "input"),
    ],
  },

  // ── Meyer Sound Speakers ───────────────────────────────────────────
  {
    id: "c0a80101-01d0-4000-8000-000000000464",
    deviceType: "speaker",
    label: "Meyer 750-LFC",
    manufacturer: "Meyer Sound",
    modelNumber: "750-LFC",
    referenceUrl: "https://meyersound.com/product/750-lfc/",
    searchTerms: ["meyer", "750", "lfc", "subwoofer", "powered", "low frequency"],
    powerDrawW: 900, // typical
    heightMm: 515,
    widthMm: 554,
    depthMm: 530,
    weightKg: 40.3,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d1-4000-8000-000000000465",
    deviceType: "speaker",
    label: "Meyer Lina",
    manufacturer: "Meyer Sound",
    modelNumber: "LINA",
    referenceUrl: "https://meyersound.com/product/lina/",
    searchTerms: ["meyer", "lina", "line array", "powered", "compact"],
    powerDrawW: 350, // typical
    heightMm: 213,
    widthMm: 515,
    depthMm: 389,
    weightKg: 19.5,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d2-4000-8000-000000000466",
    deviceType: "speaker",
    label: "Meyer Ultra-X23",
    manufacturer: "Meyer Sound",
    modelNumber: "Ultra-X23",
    referenceUrl: "https://meyersound.com/product/ultra-x23/",
    searchTerms: ["meyer", "ultra", "x23", "powered", "point source", "compact"],
    powerDrawW: 200, // typical
    heightMm: 483,
    widthMm: 191,
    depthMm: 218,
    weightKg: 12.2,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d3-4000-8000-000000000467",
    deviceType: "speaker",
    label: "Meyer UM-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPM-1P",
    referenceUrl: "https://meyersound.com/product/upm-1p/",
    searchTerms: ["meyer", "upm", "um-1p", "powered", "ultracompact"],
    powerDrawW: 200, // typical
    heightMm: 457,
    widthMm: 176,
    depthMm: 193,
    weightKg: 10,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d4-4000-8000-000000000468",
    deviceType: "speaker",
    label: "Meyer MM-4XP",
    manufacturer: "Meyer Sound",
    modelNumber: "MM-4XP",
    referenceUrl: "https://meyersound.com/product/mm-4xp/",
    searchTerms: ["meyer", "mm-4xp", "miniature", "powered", "self-powered"],
    powerDrawW: 30, // typical
    heightMm: 103,
    widthMm: 103,
    depthMm: 145,
    weightKg: 1.9,
    ports: [
      port("Audio/Power In", "analog-audio", "input", "other"),
    ],
  },
  {
    id: "c0a80101-01d5-4000-8000-000000000469",
    deviceType: "speaker",
    label: "Meyer M1D",
    manufacturer: "Meyer Sound",
    modelNumber: "M1D",
    referenceUrl: "https://meyersound.com/products/",
    searchTerms: ["meyer", "m1d", "miniature", "line array", "powered", "curvilinear"],
    powerDrawW: 100, // typical
    heightMm: 181,
    widthMm: 585,
    depthMm: 216,
    weightKg: 14.1,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d6-4000-8000-000000000470",
    deviceType: "speaker",
    label: "Meyer Ultra-X40",
    manufacturer: "Meyer Sound",
    modelNumber: "Ultra-X40",
    referenceUrl: "https://meyersound.com/product/ultra-x40/",
    searchTerms: ["meyer", "ultra", "x40", "powered", "point source"],
    powerDrawW: 300, // typical
    heightMm: 567,
    widthMm: 318,
    depthMm: 356,
    weightKg: 23.6,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01d7-4000-8000-000000000471",
    deviceType: "speaker",
    label: "Meyer UPJ-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPJ-1P",
    referenceUrl: "https://meyersound.com/product/upj-1p/",
    searchTerms: ["meyer", "upj", "powered", "compact", "vario"],
    powerDrawW: 350, // typical
    heightMm: 570,
    widthMm: 283,
    depthMm: 311,
    weightKg: 20.9,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },

  // ── d&b audiotechnik Speakers ──────────────────────────────────────
  {
    id: "c0a80101-01d8-4000-8000-000000000472",
    deviceType: "speaker",
    label: "d&b Y7P",
    manufacturer: "d&b audiotechnik",
    modelNumber: "Y7P",
    referenceUrl: "https://www.dbaudio.com/global/en/products/series/y-series/y7p/",
    searchTerms: ["d&b", "y7p", "point source", "passive", "y series"],
    powerDrawW: 0,
    heightMm: 580,
    widthMm: 257,
    depthMm: 341,
    weightKg: 18,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01d9-4000-8000-000000000473",
    deviceType: "speaker",
    label: "d&b V8",
    manufacturer: "d&b audiotechnik",
    modelNumber: "V8",
    referenceUrl: "https://www.dbaudio.com/global/en/products/series/v-series/v8/",
    searchTerms: ["d&b", "v8", "line array", "passive", "v series"],
    powerDrawW: 0,
    heightMm: 310,
    widthMm: 700,
    depthMm: 460,
    weightKg: 34,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01da-4000-8000-000000000474",
    deviceType: "speaker",
    label: "d&b V-Sub",
    manufacturer: "d&b audiotechnik",
    modelNumber: "V-SUB",
    referenceUrl: "https://www.dbaudio.com/global/en/products/series/v-series/v-sub/",
    searchTerms: ["d&b", "v-sub", "subwoofer", "passive", "v series"],
    powerDrawW: 0,
    heightMm: 606,
    widthMm: 700,
    depthMm: 728,
    weightKg: 64,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01db-4000-8000-000000000475",
    deviceType: "speaker",
    label: "d&b E8",
    manufacturer: "d&b audiotechnik",
    modelNumber: "E8",
    referenceUrl: "https://www.dbaudio.com/global/en/products/series/e-series/e8/",
    searchTerms: ["d&b", "e8", "coaxial", "passive", "point source", "e series"],
    powerDrawW: 0,
    heightMm: 390,
    widthMm: 232,
    depthMm: 223,
    weightKg: 7.3,
    ports: [
      port("Input", "speaker-level", "input", "speakon"),
      port("Link", "speaker-level", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-01dc-4000-8000-000000000476",
    deviceType: "amplifier",
    label: "d&b D20",
    manufacturer: "d&b audiotechnik",
    modelNumber: "D20",
    referenceUrl: "https://www.dbaudio.com/global/en/products/amplifiers/d20/",
    searchTerms: ["d&b", "d20", "amplifier", "4 channel"],
    powerDrawW: 3200, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 460,
    weightKg: 13.5,
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4),
      port("AES In 1-2", "aes", "input"),
      port("AES In 3-4", "aes", "input"),
      port("AES Link", "aes", "output"),
      ...ports("Speaker Out", "speaker-level", "output", 4, "speakon"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },

  // ── JBL Speakers ──────────────────────────────────────────────────
  {
    id: "c0a80101-01dd-4000-8000-000000000477",
    deviceType: "speaker",
    label: "JBL EON610",
    manufacturer: "JBL Professional",
    modelNumber: "EON610",
    referenceUrl: "https://jblpro.com/en/products/eon610",
    searchTerms: ["jbl", "eon", "610", "powered", "portable", "bluetooth"],
    powerDrawW: 250, // typical
    heightMm: 558,
    widthMm: 322,
    depthMm: 295,
    weightKg: 11.8,
    ports: [
      port("Combo In 1", "analog-audio", "input", "combo-xlr-trs"),
      port("Combo In 2", "analog-audio", "input", "combo-xlr-trs"),
      port("Loop Thru 1", "analog-audio", "output"),
      port("Loop Thru 2", "analog-audio", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-01de-4000-8000-000000000478",
    deviceType: "speaker",
    label: "JBL VRX932LAP",
    manufacturer: "JBL Professional",
    modelNumber: "VRX932LAP",
    referenceUrl: "https://jblpro.com/en/products/vrx932lap",
    searchTerms: ["jbl", "vrx", "932", "line array", "powered"],
    powerDrawW: 720, // typical
    heightMm: 349,
    widthMm: 597,
    depthMm: 444,
    weightKg: 23.6,
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01df-4000-8000-000000000479",
    deviceType: "speaker",
    label: "JBL 305P MKII",
    manufacturer: "JBL Professional",
    modelNumber: "305P MkII",
    referenceUrl: "https://jblpro.com/en-US/products/305p-mkii",
    searchTerms: ["jbl", "305p", "studio monitor", "powered", "3 series"],
    powerDrawW: 82,
    heightMm: 298,
    widthMm: 185,
    depthMm: 231,
    weightKg: 4.5,
    ports: [
      port("XLR In", "analog-audio", "input"),
      port("TRS In", "analog-audio", "input", "trs-quarter"),
      port("AC Power", "power", "input"),
    ],
  },

  // ── Other Speakers ────────────────────────────────────────────────
  {
    id: "c0a80101-01e0-4000-8000-000000000480",
    deviceType: "speaker",
    label: "EV Evolve 50",
    manufacturer: "Electro-Voice",
    modelNumber: "Evolve 50",
    referenceUrl: "https://products.electrovoice.com/na/en/evolve-50",
    searchTerms: ["electro-voice", "ev", "evolve", "50", "column", "powered", "portable"],
    powerDrawW: 150, // typical
    heightMm: 530,
    widthMm: 345,
    depthMm: 471,
    weightKg: 20.2,
    ports: [
      port("Combo In 1", "analog-audio", "input", "combo-xlr-trs"),
      port("Combo In 2", "analog-audio", "input", "combo-xlr-trs"),
      port("Link Out", "analog-audio", "output"),
      port("Mix Out", "analog-audio", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-01e1-4000-8000-000000000481",
    deviceType: "speaker",
    label: "Fostex 6301B",
    manufacturer: "Fostex",
    modelNumber: "6301B",
    referenceUrl: "https://www.fostex.jp/en/products/6301b-h/",
    searchTerms: ["fostex", "6301", "monitor", "powered", "broadcast", "compact"],
    powerDrawW: 30,
    heightMm: 188,
    widthMm: 120,
    depthMm: 118,
    weightKg: 3,
    ports: [
      port("XLR In", "analog-audio", "input"),
      port("TRS In", "analog-audio", "input", "trs-quarter"),
      port("AC Power", "power", "input"),
    ],
  },
];
