import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Switchers
  {
    id: "c0a80101-0002-4000-8000-000000000002",
    deviceType: "switcher",
    label: "Video Switcher",
    powerDrawW: 50, // typical
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("PGM Out", "sdi", "output"),
      port("PVW Out", "sdi", "output"),
      port("AUX Out", "sdi", "output"),
      port("Multiview", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Router
  {
    id: "c0a80101-0014-4000-8000-000000000020",
    deviceType: "router",
    label: "SDI Router",
    powerDrawW: 30, // typical
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Blackmagic Smart Videohub 20x20
  {
    id: "c0a80101-0015-4000-8000-000000000021",
    deviceType: "router",
    label: "BMD Videohub 20x20 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 20x20",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs",
    searchTerms: ["blackmagic", "smart videohub", "videohub", "20x20", "matrix"],
    powerDrawW: 28,
    heightMm: 44,
    widthMm: 482,
    depthMm: 236,
    weightKg: 3.6,
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("In 13", "sdi", "input"),
      port("In 14", "sdi", "input"),
      port("In 15", "sdi", "input"),
      port("In 16", "sdi", "input"),
      port("In 17", "sdi", "input"),
      port("In 18", "sdi", "input"),
      port("In 19", "sdi", "input"),
      port("In 20", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Out 13", "sdi", "output"),
      port("Out 14", "sdi", "output"),
      port("Out 15", "sdi", "output"),
      port("Out 16", "sdi", "output"),
      port("Out 17", "sdi", "output"),
      port("Out 18", "sdi", "output"),
      port("Out 19", "sdi", "output"),
      port("Out 20", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    
      port("USB-C", "usb", "bidirectional", "usb-c"),
    ],
  },
  // Blackmagic CleanSwitch 12x12
  {
    id: "c0a80101-0016-4000-8000-000000000022",
    deviceType: "router",
    label: "BMD CleanSwitch 12x12",
    manufacturer: "Blackmagic Design",
    modelNumber: "CleanSwitch 12x12",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHS-06",
    searchTerms: ["blackmagic", "videohub", "cleanswitch", "clean switch", "12x12"],
    powerDrawW: 30, // typical
    heightMm: 44,
    widthMm: 482,
    depthMm: 160,
    weightKg: 1.9,
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    
      port("RS-422", "rs422", "bidirectional", "rj45"),
    ],
  },
  // Kramer VS-88H2 — 8x8 HDMI Matrix Switcher
  {
    id: "c0a80101-0017-4000-8000-000000000023",
    deviceType: "router",
    label: "Kramer VS-88H2",
    manufacturer: "Kramer",
    modelNumber: "VS-88H2",
    referenceUrl: "https://www1.kramerav.com/us/product/vs-88h2",
    searchTerms: ["kramer", "hdmi", "matrix", "8x8", "switcher"],
    powerDrawW: 66,
    heightMm: 44,
    widthMm: 436,
    depthMm: 183,
    weightKg: 2.4,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI In 3", "hdmi", "input"),
      port("HDMI In 4", "hdmi", "input"),
      port("HDMI In 5", "hdmi", "input"),
      port("HDMI In 6", "hdmi", "input"),
      port("HDMI In 7", "hdmi", "input"),
      port("HDMI In 8", "hdmi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("HDMI Out 5", "hdmi", "output"),
      port("HDMI Out 6", "hdmi", "output"),
      port("HDMI Out 7", "hdmi", "output"),
      port("HDMI Out 8", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Video Switchers ──────────────────────────────────────────────
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-003d-4000-8000-000000000061
    // with PowerCON Distro in src/devices/infrastructure.ts, which wins the
    // dedupe (D1 keeps the last-seeded row), leaving this switcher unreachable.
    id: "c0a80101-030e-4000-8000-000000000736",
    deviceType: "switcher",
    label: "ATEM Mini",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini", "hdmi switcher"],
    powerDrawW: 30,
    heightMm: 35,
    widthMm: 238,
    depthMm: 104,
    weightKg: 0.6,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    ],
  },
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-003e-4000-8000-000000000062
    // with PowerCON Thru Distro in src/devices/infrastructure.ts, which wins
    // the dedupe, leaving this switcher unreachable.
    id: "c0a80101-030f-4000-8000-000000000737",
    deviceType: "switcher",
    label: "ATEM Mini Pro",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Pro",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini pro", "streaming"],
    powerDrawW: 30,
    heightMm: 35,
    widthMm: 238,
    depthMm: 104,
    weightKg: 0.6,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-003f-4000-8000-000000000063",
    deviceType: "switcher",
    label: "ATEM Mini Pro ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Pro ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini pro iso", "recording"],
    powerDrawW: 36,
    heightMm: 35,
    widthMm: 238,
    depthMm: 104,
    weightKg: 0.6,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0040-4000-8000-000000000064",
    deviceType: "switcher",
    label: "ATEM Mini Extreme",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Extreme",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini extreme", "8 input"],
    powerDrawW: 36,
    heightMm: 40,
    widthMm: 370,
    depthMm: 137,
    weightKg: 0.9,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("USB-C Out 1", "usb", "output", "usb-c"),
      port("USB-C Out 2", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Headphone", "analog-audio", "output", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0041-4000-8000-000000000065",
    deviceType: "switcher",
    label: "ATEM Mini Extreme ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Extreme ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini extreme iso", "8 input", "recording"],
    powerDrawW: 120,
    heightMm: 40,
    widthMm: 370,
    depthMm: 137,
    weightKg: 0.9,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("USB-C Out 1", "usb", "output", "usb-c"),
      port("USB-C Out 2", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Headphone", "analog-audio", "output", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0042-4000-8000-000000000066",
    deviceType: "switcher",
    label: "ATEM SDI",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi switcher"],
    powerDrawW: 18,
    heightMm: 35,
    widthMm: 238,
    depthMm: 119,
    weightKg: 0.7,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0043-4000-8000-000000000067",
    deviceType: "switcher",
    label: "ATEM SDI Pro ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI Pro ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi pro iso"],
    powerDrawW: 36,
    heightMm: 35,
    widthMm: 238,
    depthMm: 119,
    weightKg: 0.7,
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    ],
  },
  {
    id: "c0a80101-0044-4000-8000-000000000068",
    deviceType: "switcher",
    label: "ATEM SDI Extreme ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI Extreme ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi extreme iso", "8 input"],
    powerDrawW: 36,
    heightMm: 40,
    widthMm: 370,
    depthMm: 151,
    weightKg: 1.4,
    ports: [
      ...ports("SDI In", "sdi", "input", 8),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
    
      port("SDI Out 3", "sdi", "output"),
    
      port("SDI Out 4", "sdi", "output"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    
      port("Headphone", "analog-audio", "output", "trs-eighth"),
    
      port("USB-C Out 2", "usb", "output", "usb-c"),
    ],
  },
  {
    id: "c0a80101-0045-4000-8000-000000000069",
    deviceType: "switcher",
    label: "ATEM Television Studio HD8",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Television Studio HD8",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemtelevisionstudio",
    searchTerms: ["blackmagic", "atem", "television studio", "hd8"],
    powerDrawW: 100,
    heightMm: 161,
    widthMm: 585,
    depthMm: 375,
    weightKg: 6.8,
    ports: [
      ...ports("SDI In", "sdi", "input", 8),
      port("PGM Out", "sdi", "output"),
      port("PVW Out", "sdi", "output"),
      port("AUX Out 1", "sdi", "output"),
      port("AUX Out 2", "sdi", "output"),
      port("MV SDI Out", "sdi", "output"),
      port("MV HDMI Out", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-422", "rs422", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("SDI Out 3", "sdi", "output"),
    
      port("SDI Out 4", "sdi", "output"),
    
      port("SDI Out 5", "sdi", "output"),
    
      port("SDI Out 6", "sdi", "output"),
    
      port("SDI Out 7", "sdi", "output"),
    
      port("MADI In", "madi", "input"),
    
      port("MADI Out", "madi", "output"),
    
      port("XLR In 1", "analog-audio", "input"),
    
      port("XLR In 2", "analog-audio", "input"),
    
      port("Timecode In", "genlock", "input"),
    
      port("Timecode Out", "genlock", "output"),
    
      port("Ref In", "genlock", "input"),
    
      port("Ref Out", "genlock", "output"),
    
      port("USB-C 1", "usb", "bidirectional", "usb-c"),
    
      port("USB-C 2", "usb", "bidirectional", "usb-c"),
    ],
  },
  {
    id: "c0a80101-0046-4000-8000-000000000070",
    deviceType: "switcher",
    label: "ATEM Constellation 1 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 1 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "1me", "12g"],
    powerDrawW: 36,
    heightMm: 44,
    widthMm: 482,
    depthMm: 176,
    weightKg: 1.9,
    ports: [
      ...ports("SDI In", "sdi", "input", 10),
      ...ports("SDI Out", "sdi", "output", 6),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    ],
  },
  {
    id: "c0a80101-0047-4000-8000-000000000071",
    deviceType: "switcher",
    label: "ATEM Constellation 2 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 2 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "2me"],
    powerDrawW: 52,
    heightMm: 44,
    widthMm: 482,
    depthMm: 182,
    weightKg: 3,
    ports: [
      ...ports("SDI In", "sdi", "input", 20),
      ...ports("SDI Out", "sdi", "output", 12),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    
      port("MADI", "madi", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0048-4000-8000-000000000072",
    deviceType: "switcher",
    label: "ATEM Constellation 4 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 4 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "4me"],
    powerDrawW: 147,
    heightMm: 88,
    widthMm: 482,
    depthMm: 231,
    weightKg: 5.2,
    ports: [
      ...ports("SDI In", "sdi", "input", 40),
      ...ports("SDI Out", "sdi", "output", 24),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("MADI In", "madi", "input"),
    
      port("MADI Out 1", "madi", "output"),
    
      port("MADI Out 2", "madi", "output"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    
      port("RS-422", "rs422", "bidirectional", "rj45"),
    
      port("Analog Out L", "analog-audio", "output", "trs-quarter"),
    
      port("Analog Out R", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0049-4000-8000-000000000073",
    deviceType: "switcher",
    label: "Roland V-60HD",
    manufacturer: "Roland",
    modelNumber: "V-60HD",
    referenceUrl: "https://proav.roland.com/global/products/v-60hd/",
    searchTerms: ["roland", "v60hd", "multi-format", "switcher"],
    powerDrawW: 37,
    heightMm: 96,
    widthMm: 356,
    depthMm: 221,
    weightKg: 3,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      ...ports("SDI In", "sdi", "input", 4),
      port("HDMI PGM", "hdmi", "output"),
      port("HDMI PVW", "hdmi", "output"),
      port("HDMI MV", "hdmi", "output"),
      port("SDI PGM", "sdi", "output"),
      port("SDI PVW", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("XLR In 1", "analog-audio", "input"),
      port("XLR In 2", "analog-audio", "input"),
      port("XLR Out 1", "analog-audio", "output"),
      port("XLR Out 2", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("HDMI In 5", "hdmi", "input"),
    
      port("HDMI In 6", "hdmi", "input"),
    
      port("VGA In", "vga", "input"),
    
      port("XLR In 3", "analog-audio", "input"),
    
      port("XLR In 4", "analog-audio", "input"),
    
      port("RCA In 5", "analog-audio", "input", "rca"),
    
      port("RCA In 6", "analog-audio", "input", "rca"),
    
      port("RCA Out", "analog-audio", "output", "rca"),
    ],
  },
  {
    id: "c0a80101-004a-4000-8000-000000000074",
    deviceType: "switcher",
    label: "Barco E2 Gen 2",
    manufacturer: "Barco",
    modelNumber: "E2 Gen 2",
    referenceUrl: "https://www.barco.com/en/product/e2-gen-2",
    searchTerms: ["barco", "e2", "event master", "presentation"],
    powerDrawW: 1200, // typical
    slots: [
      { id: "e2-in-1", label: "Input Slot 1", slotFamily: "barco-em-input" },
      { id: "e2-in-2", label: "Input Slot 2", slotFamily: "barco-em-input" },
      { id: "e2-in-3", label: "Input Slot 3", slotFamily: "barco-em-input" },
      { id: "e2-in-4", label: "Input Slot 4", slotFamily: "barco-em-input" },
      { id: "e2-in-5", label: "Input Slot 5", slotFamily: "barco-em-input" },
      { id: "e2-in-6", label: "Input Slot 6", slotFamily: "barco-em-input" },
      { id: "e2-in-7", label: "Input Slot 7", slotFamily: "barco-em-input" },
      { id: "e2-in-8", label: "Input Slot 8", slotFamily: "barco-em-input" },
      { id: "e2-out-1", label: "Output Slot 1", slotFamily: "barco-em-output" },
      { id: "e2-out-2", label: "Output Slot 2", slotFamily: "barco-em-output" },
      { id: "e2-out-3", label: "Output Slot 3", slotFamily: "barco-em-output" },
      { id: "e2-out-4", label: "Output Slot 4", slotFamily: "barco-em-output" },
    ],
    heightMm: 178,
    widthMm: 483,
    depthMm: 622,
    weightKg: 31,
    ports: [
      port("Ref In", "genlock", "input"),
      port("Ref Loop Out", "genlock", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-004b-4000-8000-000000000075",
    deviceType: "switcher",
    label: "Barco S3-4K",
    manufacturer: "Barco",
    modelNumber: "S3-4K",
    referenceUrl: "https://www.barco.com/en/product/s3-4k",
    searchTerms: ["barco", "s3", "event master", "4k", "presentation"],
    powerDrawW: 650, // typical
    slots: [
      { id: "s3-in-1", label: "Input Slot 1", slotFamily: "barco-em-input" },
      { id: "s3-in-2", label: "Input Slot 2", slotFamily: "barco-em-input" },
      { id: "s3-in-3", label: "Input Slot 3", slotFamily: "barco-em-input" },
      { id: "s3-in-4", label: "Input Slot 4", slotFamily: "barco-em-input" },
      { id: "s3-out-1", label: "Output Slot 1", slotFamily: "barco-em-output" },
      { id: "s3-out-2", label: "Output Slot 2", slotFamily: "barco-em-output" },
      { id: "s3-out-3", label: "Output Slot 3", slotFamily: "barco-em-output" },
      { id: "s3-mvr-1", label: "MVR/Output Slot", slotFamily: "barco-em-output" },
    ],
    heightMm: 133,
    widthMm: 483,
    depthMm: 540,
    weightKg: 24,
    ports: [
      port("Ref In", "genlock", "input"),
      port("Ref Loop Out", "genlock", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-004c-4000-8000-000000000076",
    deviceType: "switcher",
    label: "Analog Way Aquilon C",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon C",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "presentation", "4k"],
    powerDrawW: 450, // typical
    slots: [
      { id: "aql-in-1", label: "Input Slot 1", slotFamily: "aw-aql-input" },
      { id: "aql-in-2", label: "Input Slot 2", slotFamily: "aw-aql-input" },
      { id: "aql-in-3", label: "Input Slot 3", slotFamily: "aw-aql-input" },
      { id: "aql-in-4", label: "Input Slot 4", slotFamily: "aw-aql-input" },
      { id: "aql-out-1", label: "Output Slot 1", slotFamily: "aw-aql-output" },
      { id: "aql-out-2", label: "Output Slot 2", slotFamily: "aw-aql-output" },
      { id: "aql-out-3", label: "Output Slot 3", slotFamily: "aw-aql-output" },
      { id: "aql-out-4", label: "Output Slot 4", slotFamily: "aw-aql-output" },
    ],
    heightMm: 221,
    widthMm: 482,
    depthMm: 713,
    weightKg: 30,
    ports: [
      port("Dante", "dante", "bidirectional"),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Video Routers ────────────────────────────────────────────────
  {
    id: "c0a80101-004d-4000-8000-000000000077",
    deviceType: "router",
    label: "BMD Videohub 12G 10x10",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 12G 10x10",
    referenceUrl: "https://www.blackmagicdesign.com/products/smartvideohub",
    searchTerms: ["blackmagic", "videohub", "12g", "10x10"],
    powerDrawW: 20, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 236,
    weightKg: 3,
    ports: [
      ...ports("In", "sdi", "input", 10),
      ...ports("Out", "sdi", "output", 10),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-004e-4000-8000-000000000078",
    deviceType: "router",
    label: "BMD Videohub 12G 40x40",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 12G 40x40",
    referenceUrl: "https://www.blackmagicdesign.com/products/smartvideohub",
    searchTerms: ["blackmagic", "videohub", "12g", "40x40"],
    powerDrawW: 80, // typical
    heightMm: 88,
    widthMm: 482,
    depthMm: 238,
    weightKg: 5.6,
    ports: [
      ...ports("In", "sdi", "input", 40),
      ...ports("Out", "sdi", "output", 40),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-004f-4000-8000-000000000079",
    deviceType: "router",
    label: "BMD Universal Videohub 72",
    manufacturer: "Blackmagic Design",
    modelNumber: "Universal Videohub 72",
    referenceUrl:
      "https://www.blackmagicdesign.com/products/blackmagicvideohub",
    searchTerms: [
      "blackmagic",
      "videohub",
      "universal",
      "72x72",
      "72",
      "3g",
      "modular",
      "router",
      "matrix",
    ],
    powerDrawW: 50,
    heightMm: 221,
    widthMm: 482,
    depthMm: 161,
    weightKg: 6.4,
    ports: [
      ...ports("SDI In", "sdi", "input", 72, "bnc"),
      ...ports("SDI Out", "sdi", "output", 72, "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("USB", "usb", "bidirectional", "usb-b"),
      port("RS-232", "serial", "bidirectional", "db9"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power 1", "power", "input", "iec"),
      port("AC Power 2", "power", "input", "iec"),
    ],
  },
  {
    // Re-ided 2026-08-22 (#339): shared c0a80101-0240-4000-8000-000000000721
    // with Wall Plate 1-Port Keystone in src/devices/infrastructure.ts, which
    // wins the dedupe, leaving this router unreachable.
    id: "c0a80101-031c-4000-8000-000000000750",
    deviceType: "router",
    label: "BMD Videohub 80x80 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Videohub 80x80 12G",
    referenceUrl:
      "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHS-09",
    searchTerms: [
      "blackmagic",
      "videohub",
      "80x80",
      "12g",
      "router",
      "matrix",
    ],
    powerDrawW: 92,
    heightMm: 177,
    widthMm: 483,
    depthMm: 238,
    weightKg: 10.9,
    ports: [
      ...ports("SDI In", "sdi", "input", 80, "bnc"),
      ...ports("SDI Out", "sdi", "output", 80, "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-0050-4000-8000-000000000080",
    deviceType: "router",
    label: "Lightware MX2 8x8 HDMI",
    manufacturer: "Lightware",
    modelNumber: "MX2-8x8-HDMI20",
    referenceUrl: "https://lightware.com/mx2-8x8-hdmi20",
    searchTerms: ["lightware", "mx2", "hdmi", "8x8", "matrix"],
    powerDrawW: 50, // typical
    heightMm: 44,
    widthMm: 442,
    depthMm: 278,
    weightKg: 3.2,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      ...ports("HDMI Out", "hdmi", "output", 8),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0051-4000-8000-000000000081",
    deviceType: "router",
    label: "Lightware MX2 16x16 HDMI",
    manufacturer: "Lightware",
    modelNumber: "MX2-16x16-HDMI20",
    referenceUrl: "https://lightware.com/mx2-16x16-hdmi20",
    searchTerms: ["lightware", "mx2", "hdmi", "16x16", "matrix"],
    powerDrawW: 80, // typical
    heightMm: 133,
    widthMm: 441,
    depthMm: 280,
    weightKg: 8.5,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 16),
      ...ports("HDMI Out", "hdmi", "output", 16),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0103-4000-8000-000000000335",
    deviceType: "router",
    category: "routing",
    label: "AJA KUMO 1616-12G",
    manufacturer: "AJA",
    modelNumber: "KUMO 1616-12G",
    referenceUrl: "https://www.aja.com/products/kumo-1616-12g",
    searchTerms: ["aja", "kumo", "router", "16x16", "12g", "sdi"],
    powerDrawW: 35, // typical
    heightMm: 44,
    widthMm: 442,
    depthMm: 39,
    weightKg: 0.6,
    ports: [
      ...ports("In", "sdi", "input", 16),
      ...ports("Out", "sdi", "output", 16),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Modular Routers ─────────────────────────────────────────────
  {
    id: "c0a80101-0115-4000-8000-000000000353",
    deviceType: "router",
    label: "Crestron DM-MD8X8-CPU3",
    manufacturer: "Crestron",
    modelNumber: "DM-MD8X8-CPU3",
    referenceUrl: "https://www.crestron.com/Products/Video/DigitalMedia-Modular-Matrix/Switcher-Chassis/DM-MD8X8-CPU3",
    searchTerms: ["crestron", "dm", "md8x8", "modular", "matrix", "8x8"],
    powerDrawW: 80, // typical
    slots: [
      { id: "dm8-in-1", label: "Input Slot 1", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-2", label: "Input Slot 2", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-3", label: "Input Slot 3", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-4", label: "Input Slot 4", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-5", label: "Input Slot 5", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-6", label: "Input Slot 6", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-7", label: "Input Slot 7", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-8", label: "Input Slot 8", slotFamily: "crestron-dm-input" },
      { id: "dm8-out-1", label: "Output Slot 1", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-2", label: "Output Slot 2", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-3", label: "Output Slot 3", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-4", label: "Output Slot 4", slotFamily: "crestron-dm-output" },
    ],
    heightMm: 177,
    widthMm: 485,
    depthMm: 459,
    weightKg: 9.1,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0116-4000-8000-000000000354",
    deviceType: "router",
    label: "Crestron DM-MD16X16-CPU3",
    manufacturer: "Crestron",
    modelNumber: "DM-MD16X16-CPU3",
    referenceUrl: "https://www.crestron.com/Products/Video/DigitalMedia-Modular-Matrix/Switcher-Chassis/DM-MD16X16-CPU3",
    searchTerms: ["crestron", "dm", "md16x16", "modular", "matrix", "16x16"],
    powerDrawW: 120, // typical
    slots: [
      { id: "dm16-in-1", label: "Input Slot 1", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-2", label: "Input Slot 2", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-3", label: "Input Slot 3", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-4", label: "Input Slot 4", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-5", label: "Input Slot 5", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-6", label: "Input Slot 6", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-7", label: "Input Slot 7", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-8", label: "Input Slot 8", slotFamily: "crestron-dm-input" },
      { id: "dm16-out-1", label: "Output Slot 1", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-2", label: "Output Slot 2", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-3", label: "Output Slot 3", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-4", label: "Output Slot 4", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-5", label: "Output Slot 5", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-6", label: "Output Slot 6", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-7", label: "Output Slot 7", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-8", label: "Output Slot 8", slotFamily: "crestron-dm-output" },
    ],
    heightMm: 311,
    widthMm: 485,
    depthMm: 398,
    weightKg: 12.9,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0117-4000-8000-000000000355",
    deviceType: "router",
    label: "Lightware MX2M-FR24R",
    manufacturer: "Lightware",
    modelNumber: "MX2M-FR24R",
    referenceUrl: "https://lightware.com/mx2m-fr24r-rf",
    searchTerms: ["lightware", "mx2m", "fr24r", "modular", "matrix", "24x24"],
    powerDrawW: 100, // typical
    slots: [
      { id: "mx2m-in-1", label: "Video Input Slot 1", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-2", label: "Video Input Slot 2", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-3", label: "Video Input Slot 3", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-4", label: "Video Input Slot 4", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-5", label: "Video Input Slot 5", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-6", label: "Video Input Slot 6", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-out-1", label: "Video Output Slot 1", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-2", label: "Video Output Slot 2", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-3", label: "Video Output Slot 3", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-4", label: "Video Output Slot 4", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-5", label: "Video Output Slot 5", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-6", label: "Video Output Slot 6", slotFamily: "lightware-mx2m-video-out" },
    ],
    heightMm: 355,
    widthMm: 483,
    depthMm: 473,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Fixed-Port Routers ──────────────────────────────────────────
  {
    id: "c0a80101-0118-4000-8000-000000000356",
    deviceType: "router",
    label: "Extron DTP CrossPoint 84 4K",
    manufacturer: "Extron",
    modelNumber: "DTP CrossPoint 84 4K",
    referenceUrl: "https://www.extron.com/product/dtpcp4k84",
    searchTerms: ["extron", "dtp", "crosspoint", "84", "4k", "matrix"],
    powerDrawW: 60, // typical
    heightMm: 89,
    widthMm: 432,
    depthMm: 389,
    weightKg: 5.2,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 6),
      ...ports("HDBaseT In", "hdbaset", "input", 2),
      ...ports("HDMI Out", "hdmi", "output", 2),
      ...ports("HDBaseT Out", "hdbaset", "output", 2),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0119-4000-8000-000000000357",
    deviceType: "router",
    label: "Extron DTP CrossPoint 108 4K",
    manufacturer: "Extron",
    modelNumber: "DTP CrossPoint 108 4K",
    referenceUrl: "https://www.extron.com/product/dtpcp4k108",
    searchTerms: ["extron", "dtp", "crosspoint", "108", "4k", "matrix"],
    powerDrawW: 80, // typical
    heightMm: 133,
    widthMm: 432,
    depthMm: 389,
    weightKg: 7.4,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 6),
      ...ports("HDBaseT In", "hdbaset", "input", 4),
      ...ports("HDMI Out", "hdmi", "output", 4),
      ...ports("HDBaseT Out", "hdbaset", "output", 4),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Ross Ultrix Modular Routers ────────────────────────────────────
  {
    id: "c0a80101-0167-4000-8000-000000000359",
    deviceType: "router",
    label: "Ross Ultrix FR5",
    manufacturer: "Ross Video",
    modelNumber: "ULTRIX-FR5",
    referenceUrl:
      "https://www.rossvideo.com/products/routing-systems/ultrix/ultrix-specifications/",
    searchTerms: ["ross", "ultrix", "fr5", "160x160", "modular", "router"],
    powerDrawW: 500, // typical
    slots: [
      { id: "ufr5-slot-1", label: "Slot 1", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-2", label: "Slot 2", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-3", label: "Slot 3", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-4", label: "Slot 4", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-5", label: "Slot 5", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-6", label: "Slot 6", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-7", label: "Slot 7", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-8", label: "Slot 8", slotFamily: "ross-ultrix" },
      { id: "ufr5-slot-9", label: "Slot 9", slotFamily: "ross-ultrix" },
    ],
    heightMm: 221,
    widthMm: 445,
    depthMm: 201,
    weightKg: 6.4,
    ports: [
      ...ports("Ethernet", "ethernet", "bidirectional", 2, "ethercon"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0168-4000-8000-000000000360",
    deviceType: "router",
    label: "Ross Ultrix FR2",
    manufacturer: "Ross Video",
    modelNumber: "ULTRIX-FR2",
    referenceUrl:
      "https://www.rossvideo.com/products/routing-systems/ultrix/ultrix-specifications/",
    searchTerms: ["ross", "ultrix", "fr2", "72x72", "modular", "router"],
    powerDrawW: 300, // typical
    slots: [
      { id: "ufr2-slot-1", label: "Slot 1", slotFamily: "ross-ultrix" },
      { id: "ufr2-slot-2", label: "Slot 2", slotFamily: "ross-ultrix" },
      { id: "ufr2-slot-3", label: "Slot 3", slotFamily: "ross-ultrix" },
      { id: "ufr2-sfp-1", label: "AUX SFP 1", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "ufr2-sfp-2", label: "AUX SFP 2", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
    heightMm: 88,
    widthMm: 445,
    depthMm: 201,
    weightKg: 5.4,
    ports: [
      ...ports("SDI In", "sdi", "input", 16, "bnc"),
      ...ports("SDI Out", "sdi", "output", 16, "bnc"),
      ...ports("Ethernet", "ethernet", "bidirectional", 2, "ethercon"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0169-4000-8000-000000000361",
    deviceType: "router",
    label: "Ross Ultrix FR1",
    manufacturer: "Ross Video",
    modelNumber: "ULTRIX-FR1",
    referenceUrl:
      "https://www.rossvideo.com/products/routing-systems/ultrix/ultrix-specifications/",
    searchTerms: ["ross", "ultrix", "fr1", "36x36", "modular", "router"],
    powerDrawW: 200, // typical
    slots: [
      { id: "ufr1-slot-1", label: "Slot 1", slotFamily: "ross-ultrix" },
      { id: "ufr1-sfp-1", label: "AUX SFP 1", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
      { id: "ufr1-sfp-2", label: "AUX SFP 2", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
    heightMm: 44,
    widthMm: 445,
    depthMm: 201,
    weightKg: 4.1,
    ports: [
      ...ports("SDI In", "sdi", "input", 16, "bnc"),
      ...ports("SDI Out", "sdi", "output", 16, "bnc"),
      ...ports("Ethernet", "ethernet", "bidirectional", 2, "ethercon"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Ross Carbonite Black ───────────────────────────────────────────
  {
    id: "c0a80101-016a-4000-8000-000000000362",
    deviceType: "switcher",
    label: "Ross Carbonite Black 2 M/E",
    manufacturer: "Ross Video",
    modelNumber: "Carbonite Black 2 M/E",
    referenceUrl:
      "https://www.rossvideo.com/live-production/production-switchers/carbonite-black/specifications/",
    searchTerms: [
      "ross",
      "carbonite",
      "black",
      "2me",
      "production",
      "switcher",
    ],
    powerDrawW: 250, // typical
    heightMm: 89,
    widthMm: 481,
    depthMm: 437,
    weightKg: 7,
    ports: [
      ...ports("SDI In", "sdi", "input", 36, "bnc"),
      ...ports("SDI Out", "sdi", "output", 22, "bnc"),
      ...ports("Ethernet", "ethernet", "bidirectional", 2, "rj45"),
      port("RS-422", "serial", "bidirectional", "db9"),
      ...ports("Ref Out", "genlock", "output", 2, "bnc"),
      ...ports("AES Out", "aes", "output", 2),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Blackmagic ATEM ────────────────────────────────────────────────
  {
    id: "c0a80101-016b-4000-8000-000000000363",
    deviceType: "switcher",
    label: "BMD ATEM Television Studio Pro 4K",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Television Studio Pro 4K",
    referenceUrl:
      "https://www.blackmagicdesign.com/products/atemtelevisionstudiopro4k/techspecs",
    searchTerms: [
      "blackmagic",
      "atem",
      "television studio",
      "pro 4k",
      "production",
      "switcher",
    ],
    powerDrawW: 80, // typical
    heightMm: 161,
    widthMm: 426,
    depthMm: 373,
    weightKg: 4.9,
    ports: [
      ...ports("SDI In", "sdi", "input", 8, "bnc"),
      ...ports("SDI PGM Out", "sdi", "output", 9, "bnc"),
      port("SDI MV Out", "sdi", "output", "bnc"),
      port("HDMI MV Out", "hdmi", "output"),
      ...ports("XLR In", "analog-audio", "input", 2, "xlr-3"),
      port("Ref In", "genlock", "input", "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-016c-4000-8000-000000000364",
    deviceType: "control-processor",
    label: "BMD ATEM 2 M/E Advanced Panel 20",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 2 M/E Advanced Panel 20",
    referenceUrl:
      "https://www.blackmagicdesign.com/products/atemconstellation8k/techspecs/W-ABP-05",
    searchTerms: [
      "blackmagic",
      "atem",
      "advanced panel",
      "2me",
      "control",
      "panel",
    ],
    powerDrawW: 30, // typical
    heightMm: 166,
    widthMm: 725,
    depthMm: 483,
    weightKg: 11,
    ports: [
      ...ports("Ethernet", "ethernet", "bidirectional", 4, "rj45"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  // ── AJA KUMO ──────────────────────────────────────────────────────
  {
    id: "c0a80101-016d-4000-8000-000000000365",
    deviceType: "router",
    label: "AJA KUMO 3232-12G",
    manufacturer: "AJA",
    modelNumber: "KUMO 3232-12G",
    referenceUrl: "https://www.aja.com/products/kumo-3232-12g",
    searchTerms: ["aja", "kumo", "3232", "32x32", "12g", "sdi", "router"],
    powerDrawW: 75, // typical
    heightMm: 89,
    widthMm: 442,
    depthMm: 39,
    weightKg: 1,
    ports: [
      ...ports("SDI In", "sdi", "input", 32, "bnc"),
      ...ports("SDI Out", "sdi", "output", 32, "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("Ref In", "genlock", "input", "bnc"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-016e-4000-8000-000000000366",
    deviceType: "control-processor",
    label: "AJA KUMO CP",
    manufacturer: "AJA",
    modelNumber: "KUMO CP",
    referenceUrl: "https://www.aja.com/products/kumo-cp",
    searchTerms: ["aja", "kumo", "cp", "control", "panel", "router"],
    powerDrawW: 10, // typical
    heightMm: 44,
    widthMm: 442,
    depthMm: 33,
    weightKg: 0.5,
    ports: [
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("RS-422", "serial", "bidirectional", "db9"),
      port("DC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-016f-4000-8000-000000000367",
    deviceType: "control-processor",
    label: "AJA KUMO CP2",
    manufacturer: "AJA",
    modelNumber: "KUMO CP2",
    referenceUrl: "https://www.aja.com/products/kumo-cp2",
    searchTerms: ["aja", "kumo", "cp2", "control", "panel", "router", "2ru"],
    powerDrawW: 12, // typical
    heightMm: 89,
    widthMm: 442,
    depthMm: 33,
    weightKg: 1,
    ports: [
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("DC Power", "power", "input"),
    ],
  },
  // ── BMD Universal Videohub ─────────────────────────────────────────
  {
    id: "c0a80101-0170-4000-8000-000000000368",
    deviceType: "router",
    label: "BMD Videohub 120x120 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Videohub 120x120 12G",
    referenceUrl:
      "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHB-09",
    searchTerms: [
      "blackmagic",
      "videohub",
      "120x120",
      "12g",
      "universal",
      "router",
    ],
    powerDrawW: 350, // typical
    heightMm: 266,
    widthMm: 483,
    depthMm: 142,
    weightKg: 15,
    ports: [
      ...ports("SDI In", "sdi", "input", 120, "bnc"),
      ...ports("SDI Out", "sdi", "output", 120, "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("Ref In", "genlock", "input", "bnc"),
      port("Ref Loop", "genlock", "output", "bnc"),
      port("AC Power 1", "power", "input", "iec"),
      port("AC Power 2", "power", "input", "iec"),
    ],
  },
  // ── Lightware Matrix ───────────────────────────────────────────────
  {
    id: "c0a80101-0171-4000-8000-000000000369",
    deviceType: "router",
    label: "Lightware MX2-24x24-HDMI20",
    manufacturer: "Lightware",
    modelNumber: "MX2-24x24-HDMI20",
    referenceUrl: "https://lightware.com/mx2-24x24-hdmi20",
    searchTerms: [
      "lightware",
      "mx2",
      "24x24",
      "hdmi",
      "matrix",
      "4k",
    ],
    powerDrawW: 120, // typical
    heightMm: 177,
    widthMm: 441,
    depthMm: 280,
    weightKg: 9.3,
    ports: [
      ...ports("HDMI In", "hdmi", "input", 24),
      ...ports("HDMI Out", "hdmi", "output", 24),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("Serial", "serial", "bidirectional", "phoenix"),
      port("USB", "usb", "bidirectional", "usb-b"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  // ── Analog Way Aquilon RS6 ─────────────────────────────────────────
  {
    id: "c0a80101-0172-4000-8000-000000000370",
    deviceType: "switcher",
    label: "Analog Way Aquilon RS6",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon RS6",
    referenceUrl: "https://www.analogway.com/products/aquilon-rs6",
    searchTerms: [
      "analog way",
      "aquilon",
      "rs6",
      "presentation",
      "4k",
      "8k",
    ],
    powerDrawW: 600, // typical
    slots: [
      {
        id: "rs6-in-1",
        label: "Input Slot 1",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-in-2",
        label: "Input Slot 2",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-in-3",
        label: "Input Slot 3",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-in-4",
        label: "Input Slot 4",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-in-5",
        label: "Input Slot 5",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-in-6",
        label: "Input Slot 6",
        slotFamily: "aw-aql-input",
      },
      {
        id: "rs6-out-1",
        label: "Output Slot 1",
        slotFamily: "aw-aql-output",
      },
      {
        id: "rs6-out-2",
        label: "Output Slot 2",
        slotFamily: "aw-aql-output",
      },
      {
        id: "rs6-out-3",
        label: "Output Slot 3",
        slotFamily: "aw-aql-output",
      },
      {
        id: "rs6-out-4",
        label: "Output Slot 4",
        slotFamily: "aw-aql-output",
      },
    ],
    ports: [
      ...ports("HDMI Dedicated Out", "hdmi", "output", 2),
      port("Dante", "dante", "bidirectional"),
      port("Ref In", "genlock", "input", "bnc"),
      port("Ref Loop", "genlock", "output", "bnc"),
      port("Ethernet", "ethernet", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Analog Way RC400T Controller ───────────────────────────────────
  {
    id: "c0a80101-0173-4000-8000-000000000371",
    deviceType: "control-processor",
    label: "Analog Way RC400T",
    manufacturer: "Analog Way",
    modelNumber: "RC400T",
    referenceUrl: "https://www.analogway.com/products/rc400t",
    searchTerms: [
      "analog way",
      "rc400t",
      "controller",
      "livepremier",
      "midra",
    ],
    powerDrawW: 25, // typical
    heightMm: 123,
    widthMm: 570,
    depthMm: 382,
    weightKg: 8,
    ports: [
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
];
