import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Wireless Video
  // Teradek Bolt 4K 750 TX — Wireless Video Transmitter
  {
    id: "c0a80101-002e-4000-8000-000000000046",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K TX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K 750 TX",
    referenceUrl: "https://teradek.com/products/bolt-4k-750-set",
    searchTerms: ["teradek", "bolt", "wireless", "transmitter", "zero delay"],
    powerDrawW: 14, // typical
    heightMm: 27,
    widthMm: 91,
    depthMm: 132,
    weightKg: 0.4,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Teradek Bolt 4K 750 RX — Wireless Video Receiver
  {
    id: "c0a80101-002f-4000-8000-000000000047",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K RX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K 750 RX",
    referenceUrl: "https://teradek.com/products/bolt-4k-750-rx-only",
    searchTerms: ["teradek", "bolt", "wireless", "receiver", "zero delay"],
    powerDrawW: 14, // typical
    heightMm: 27,
    widthMm: 139,
    depthMm: 112,
    weightKg: 0.4,
    ports: [
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Intercom
  // ClearCom FreeSpeak II Base Station
  {
    id: "c0a80101-0030-4000-8000-000000000048",
    deviceType: "intercom",
    label: "ClearCom FreeSpeak II",
    manufacturer: "Clear-Com",
    modelNumber: "FreeSpeak II Base Station",
    referenceUrl: "https://www.clearcom.com/Products/Products-By-Name/Station-IC/fsii-base-ii",
    searchTerms: ["clearcom", "clear-com", "freespeak", "wireless intercom", "base station"],
    powerDrawW: 60, // typical
    heightMm: 43,
    widthMm: 483,
    depthMm: 259,
    weightKg: 2.5,
    ports: [
      port("Partyline 1", "analog-audio", "bidirectional"),
      port("Partyline 2", "analog-audio", "bidirectional"),
      port("Partyline 3", "analog-audio", "bidirectional"),
      port("Partyline 4", "analog-audio", "bidirectional"),
      port("4-Wire 1", "analog-audio", "bidirectional"),
      port("4-Wire 2", "analog-audio", "bidirectional"),
      port("Program In", "analog-audio", "input"),
      port("Stage Announce", "analog-audio", "output"),
      port("GPIO", "gpio", "bidirectional"),
      port("LAN 1", "ethernet", "bidirectional"),
      port("LAN 2", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-007a-4000-8000-000000000122",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K MAX TX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K MAX TX",
    referenceUrl: "https://teradek.com/products/bolt-4k-max",
    searchTerms: ["teradek", "bolt", "max", "wireless", "transmitter"],
    powerDrawW: 18, // typical
    heightMm: 27,
    widthMm: 91,
    depthMm: 132,
    weightKg: 0.7,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-007b-4000-8000-000000000123",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K MAX RX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K MAX RX",
    referenceUrl: "https://teradek.com/products/bolt-4k-max",
    searchTerms: ["teradek", "bolt", "max", "wireless", "receiver"],
    powerDrawW: 18, // typical
    heightMm: 27,
    widthMm: 139,
    depthMm: 112,
    weightKg: 0.7,
    ports: [
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Intercom ─────────────────────────────────────────────────────
  {
    id: "c0a80101-00a3-4000-8000-000000000163",
    deviceType: "intercom",
    label: "Riedel Artist",
    manufacturer: "Riedel",
    modelNumber: "Artist",
    referenceUrl: "https://www.riedel.net/products-solutions/intercom/artist/",
    searchTerms: ["riedel", "artist", "matrix intercom", "digital"],
    powerDrawW: 200, // typical
    heightMm: 88,
    widthMm: 483,
    depthMm: 404,
    weightKg: 6.3,
    ports: [
      port("MADI 1", "madi", "bidirectional"),
      port("MADI 2", "madi", "bidirectional"),
      port("Dante", "dante", "bidirectional"),
      ...ports("4-Wire", "analog-audio", "bidirectional", 4),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a4-4000-8000-000000000164",
    deviceType: "intercom",
    label: "Riedel Bolero",
    manufacturer: "Riedel",
    modelNumber: "Bolero",
    referenceUrl: "https://www.riedel.net/products-solutions/intercom/bolero/",
    searchTerms: ["riedel", "bolero", "wireless intercom", "dect"],
    powerDrawW: 30, // typical (antenna base)
    ports: [
      port("4-Wire In", "analog-audio", "input"),
      port("4-Wire Out", "analog-audio", "output"),
      port("AES In", "aes", "input"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a5-4000-8000-000000000165",
    deviceType: "intercom",
    label: "Clear-Com Eclipse HX",
    manufacturer: "Clear-Com",
    modelNumber: "Eclipse HX",
    referenceUrl: "https://www.clearcom.com/Products/Products-By-Name/Station-IC/eclipse-hx-median",
    searchTerms: ["clearcom", "clear-com", "eclipse", "matrix intercom"],
    powerDrawW: 150, // typical
    heightMm: 264,
    widthMm: 482,
    depthMm: 410,
    weightKg: 20,
    ports: [
      ...ports("4-Wire", "analog-audio", "bidirectional", 4),
      port("MADI", "madi", "bidirectional"),
      port("Dante", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00a6-4000-8000-000000000166",
    deviceType: "intercom",
    label: "Clear-Com FreeSpeak Edge",
    manufacturer: "Clear-Com",
    modelNumber: "FreeSpeak Edge",
    referenceUrl: "https://www.clearcom.com/Products/Products-By-Name/Wireless/FreeSpeak-Edge",
    searchTerms: ["clearcom", "clear-com", "freespeak", "edge", "wireless intercom"],
    powerDrawW: 70, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 354,
    weightKg: 3.3,
    ports: [
      ...ports("Partyline", "analog-audio", "bidirectional", 4),
      port("4-Wire In", "analog-audio", "input"),
      port("4-Wire Out", "analog-audio", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Dante Primary", "dante", "bidirectional"),
    
      port("Dante Secondary", "dante", "bidirectional"),
    ],
  },
];
